using PoLaKoSz.MusicFM.Models;
using System.Collections.Generic;

namespace PoLaKoSz.MusicFM.Tests.Integration.StaticResources.MusicKillers
{
    public static class DannyL
    {
        public static readonly List<Music> Tracklist;



        static DannyL()
        {
            Tracklist = new List<Music>()
            {
                new Music("Vetboten Berlin ft. Running Touch - If i Give It To You (Tube & Berger Remix)"),
                new Music("Leon & Dennis Cruz - My Hood"),
                new Music("Michael Bibi - Hanging Tree"),
                new Music("Paces ft. Emmalyn & Jeida Woods - Tecnique (Torren Foot Remix)"),
                new Music("Denney - Empire"),
                new Music("Elderbrook - Capricorn (Claude Vonstroke Remix)"),
                new Music("Frederick & Krusse - Reach Out"),
                new Music("Boston Bun - Better Together"),
                new Music("Axwell - Nobody Else"),
                new Music("Curtis Alto - Sunday"),
                new Music("Camelphat & Jem Cooke & Cristoph - Breathe"),
                new Music("Handbreakes - Discow"),
                new Music("Boston Bun - Better Together"),
                new Music("Jodie Conor & Solo Suspex - Back To You (Fitz & Baron Remix)"),
                new Music("LMC & Mark McCabe - Time To Groove"),
                new Music("Fisher - Ya Kidding (Eli Brown Remix)"),
                new Music("Elderbrook - Capricorn (Claude Vonstroke Remix)"),
                new Music("Biscits - Socialize"),
                new Music("Strafe - Set It Off (Justin Martin Remix)"),
                new Music("Biscits - Do It Like This"),
                new Music("Eli Brown & Solo Tamas - Lucky"),
                new Music("Kinnerman - Promised Land"),
                new Music("Del-30 - WHP"),
                new Music("Offaiah - Work It Out"),
                new Music("Mick Mazoo - Avoir"),
                new Music("Dombresky - Futurmastic"),
                new Music("Silk City & Dua Lipa - ElectryCity (The Black Madonna Remix)"),
                new Music("Mark Knight & Danny Howard - You Can Do It Baby"),
                new Music("OT - Where Is My Love (Brieuc & Gregor Potter Remix)"),
                new Music("Lee Foss & Eli Brown - Freak You Right"),
                new Music("Kinnerman - Promised Land"),
                new Music("Del-30 - WHP"),
                new Music("Ember - BYO"),
                new Music("Otosan - Loghts (Dave Winnel Remix)"),
                new Music("Solberjum - Choices"),
                new Music("Lukas - Still In Love"),
                new Music("Mogusa & Mick Mazoo - Anatomy"),
                new Music("Sebjak & Sleepwalkers - 1989"),
                new Music("Freiboitar - Back Jack"),
                new Music("Fenixpawl & Dave Winnel - Find A Way (Stace Cadet Remix)"),
                new Music("Sunnery James & Ryan Marciano ft. Kess Kross - Coffeshop"),
                new Music("Basement Jaxx - Bingo Bango (Tom Staar & Kryder Remix)"),
                new Music("Tom Staar & SM - Bombs Away"),
                new Music("Axwell & Ingrosso ft. Romans - Dancing (Brohug Remix)"),
                new Music("Kungs & Stargate - Be Right There (Tony Romera Remix)"),
                new Music("Armin Van Buuren & James Newman - Therapy (Throttle Remix)"),
                new Music("Mercer - Alright"),
                new Music("Nic & Mark Fanciulli - Star"),
                new Music("Kyro - Koko Bean"),
                new Music("Aevion - Wild Safari"),
                new Music("Becky Hill - Surise In The East (Michael Calfan Remix)"),
                new Music("Tobtok & Adrian Lux - As I Sleep (Bode Remix)"),
                new Music("Ten Ven - Just About"),
                new Music("Aevion - Telling Me"),
                new Music("Kungs & Stargate GOLDN - Be Right Here"),
                new Music("Valentino Khan - Feel Your Love"),
                new Music("Axwell & Ingrosso ft. Romans - Dancing Alone"),
                new Music("Chris Lake & Destructo & Breach - J.O.D.O Jack (Muzzaik Edit)"),
                new Music("Fisher - Losing It"),
                new Music("Eli Brown - Wait No More"),
                new Music("Au/Ra & Camelphat - Panic Room (Jonas Rathsman Remix)"),
                new Music("Joris Voorn - District Seven"),
                new Music("Freiboitar - Back Jack"),
                new Music("Fenixpawl & Dave Winnel - Find A Way (Stace Cadet Remix)"),
                new Music("Sunnery James & Ryan Marciano ft. Kess Kross - Coffeshop"),
                new Music("Basement Jaxx - Bingo Bango (Tom Staar & Kryder Remix)"),
                new Music("Tom Staar & SM - Bombs Away"),
                new Music("Axwell & Ingrosso ft. Romans - Dancing (Brohug Remix)"),
                new Music("Kungs & Stargate - Be Right There (Tony Romera Remix)"),
                new Music("Armin Van Buuren & James Newman - Therapy (Throttle Remix)"),
                new Music("Mercer - Alright"),
                new Music("Nic & Mark Fanciulli - Star"),
                new Music("Kyro - Koko Bean"),
                new Music("Aevion - Wild Safari"),
                new Music("LK - I Wanna Make Luv 2 U"),
                new Music("Semedo - Make Me Groove"),
                new Music("Boston Bun ft. DVNO - Spread Love (Mercer Remix)"),
                new Music("Just Kiddin - Body Talk (Tommy Mc Remix)"),
                new Music("Junior Sanchez - Strong Enough"),
                new Music("Mercer - Fireworks"),
                new Music("Purple Disco Machine - Dished Male Stripper (Illyus & Barrientos Remix)"),
                new Music("Sterling Void - it’s Alright (Mark Knight Remix)"),
                new Music("Malaa - Cash Money"),
                new Music("Steve Angello & Kryder - Romani"),
                new Music("Bolier & Trobi - In The Water (BLR Festival Remix)"),
                new Music("Moguai & Raumakustik - The Greatest Speech"),
                new Music("Freiboitar - Back Jack"),
                new Music("Fenixpawl & Dave Winnel - Find A Way (Stace Cadet Remix)"),
                new Music("Sunnery James & Ryan Marciano ft. Kess Kross - Coffeshop"),
                new Music("Basement Jaxx - Bingo Bango (Tom Staar & Kryder Remix)"),
                new Music("Tom Staar & SM - Bombs Away"),
                new Music("Axwell & Ingrosso ft. Romans - Dancing (Brohug Remix)"),
                new Music("Kungs & Stargate - Be Right There (Tony Romera Remix)"),
                new Music("Armin Van Buuren & James Newman - Therapy (Throttle Remix)"),
                new Music("Mercer - Alright"),
                new Music("Nic & Mark Fanciulli - Star"),
                new Music("Kyro - Koko Bean"),
                new Music("Aevion - Wild Safari"),
                new Music("Icarus - Flowers"),
                new Music("Fred Rister & Sam Martin & Chris Willis - I Want a Miracle (Kc Lights Remix)"),
                new Music("Gorgon City ft. Kamille - Go Deep"),
                new Music("Kideko - Good Thing"),
                new Music("Tom Tyger - Infinity"),
                new Music("Dj Koze - Pick Up"),
                new Music("Aevion - Heartbeat"),
                new Music("Loud Luxury ft. Brando - Body (Dirtcaps Remix)"),
                new Music("Polymod - No Other"),
                new Music("Petit Biscuit - Waterfall (Karma Kid & Fono Remix)"),
                new Music("Airwolf - Elevate"),
                new Music("Pional - Tempest"),
                new Music("George Fitzgerald - Frieda"),
                new Music("Michael Calfan - I’t s Wrong (Rollercoaster Vip Mix)"),
                new Music("Martin Solveig - My Love (Kolsch Remix)"),
                new Music("Tchami - Aura"),
                new Music("Feenixpawl & Dave Winnel - Find A Way (Stace Cadet Extended Remix)"),
                new Music("Just Kiddin - Body Talk (Tommy Mc Remix)"),
                new Music("Kungs & Stargate - Be Right There (Tony Romera Remix)"),
                new Music("Calvin Harris & Sam Smith - Pomises (Sonny Fodera Remix)"),
                new Music("Dom Dolla - Take It (ZDS Remix)"),
                new Music("Leon (Italy) & Dennos Cruz - My Hood"),
                new Music("Sonny Fodera & Josh Barry - Need"),
                new Music("Apexape & Carla Monroe - Whisky & Cola (The Golden Boys Remix)"),
                new Music("The Alexsander - Rains"),
                new Music("Alessia Cara - Growing Pains (Dombresky Remix)"),
                new Music("Gypsy Woman - (Richey Profond Remix"),
                new Music("TEPR - Taste Of Love"),
                new Music("Junior Sanchez - Strong Enough"),
                new Music("Rhythm Masters @ MYNC - I Feel Love"),
                new Music("Adelphi Music Factory - Javelin"),
                new Music("Secondcity - Tomorrow’s World"),
                new Music("Ce Ce Peniston vs Sand B - Finally Make The World Go Round (Ben Rainey & Tommy MC edit)"),
                new Music("Junior Jack - See You Dancin"),
                new Music("Bob Sinclar - I Feel Love (Erick Morillo Edit)"),
                new Music("LK - I Wanna Make Luv 2 U"),
                new Music("Semedo - Make Me Groove"),
                new Music("Boston Bun ft. DVNO - Spread Love (Mercer Remix)"),
                new Music("Just Kiddin - Body Talk (Tommy Mc Remix)"),
                new Music("Junior Sanchez - Strong Enough"),
                new Music("Mercer - Fireworks"),
                new Music("Purple Disco Machine - Dished Male Stripper (Illyus & Barrientos Remix)"),
                new Music("Sterling Void - it’s Alright (Mark Knight Remix)"),
                new Music("Malaa - Cash Money"),
                new Music("Steve Angello & Kryder - Romani"),
                new Music("Bolier & Trobi - In The Water (BLR Festival Remix)"),
                new Music("Moguai & Raumakustik - The Greatest Speech"),
                new Music("Freiboitar - Back Jack"),
                new Music("Fenixpawl & Dave Winnel - Find A Way (Stace Cadet Remix)"),
                new Music("Sunnery James & Ryan Marciano ft. Kess Kross - Coffeshop"),
                new Music("Basement Jaxx - Bingo Bango (Tom Staar & Kryder Remix)"),
                new Music("Tom Staar & SM - Bombs Away"),
                new Music("Axwell & Ingrosso ft. Romans - Dancing (Brohug Remix)"),
                new Music("Kungs & Stargate - Be Right There (Tony Romera Remix)"),
                new Music("Armin Van Buuren & James Newman - Therapy (Throttle Remix)"),
                new Music("Mercer - Alright"),
                new Music("Nic & Mark Fanciulli - Star"),
                new Music("Kyro - Koko Bean"),
                new Music("Aevion - Wild Safari"),
                new Music("SG Lewis ft Aluna George - Hurting"),
                new Music("Disclosure - Moonlight"),
                new Music("Cosmo’s Midnight ft Kucka - Ealk With Me (Koa Remix)"),
                new Music("Black Coffee vs David Guetta - Drive"),
                new Music("Burns - Hands On Me (Blonde Remix)"),
                new Music("Shift K3y ft. AME - Entitetry (Weiss Remix)"),
                new Music("Catz ‘N Dogz - Factory Settings"),
                new Music("Toyboy & Robin - Horn It"),
                new Music("Tom Tyger vs Charle B & VCTRY - One Too Many"),
                new Music("Tom Staar & Eddie Thoneick - Otherside"),
                new Music("Mala - Bling Bling (Volac remix)"),
                new Music("Mercer - Fireworks"),
                new Music("Kungs & Stargate GOLDN - Be Right Here"),
                new Music("Alessia Cara - Growing Pains (Dombresky Remix)"),
                new Music("Becky Hill - Surise In The East (Michael Calfan Remix)"),
                new Music("Tobtok & Adrian Lux - As I Sleep (Bode Remix)"),
                new Music("Ten Ven - Just About"),
                new Music("Aevion - Telling Me"),
                new Music("Kungs & Stargate GOLDN - Be Right Here"),
                new Music("Valentino Khan - Feel Your Love"),
                new Music("Axwell & Ingrosso ft. Romans - Dancing Alone"),
                new Music("Chris Lake & Destructo & Breach - J.O.D.O Jack (Muzzaik Edit)"),
                new Music("Fisher - Losing It"),
                new Music("Eli Brown - Wait No More"),
                new Music("Au/Ra & Camelphat - Panic Room (Jonas Rathsman Remix)"),
                new Music("Joris Voorn - District Seven"),
                new Music("Icarus - Flowers"),
                new Music("Fred Rister & Sam Martin & Chris Willis - I Want a Miracle (Kc Lights Remix)"),
                new Music("Gorgon City ft. Kamille - Go Deep"),
                new Music("Kideko - Good Thing"),
                new Music("Tom Tyger - Infinity"),
                new Music("Dj Koze - Pick Up"),
                new Music("Aevion - Heartbeat"),
                new Music("Loud Luxury ft. Brando - Body (Dirtcaps Remix)"),
                new Music("Polymod - No Other"),
                new Music("Petit Biscuit - Waterfall (Karma Kid & Fono Remix)"),
                new Music("Airwolf - Elevate"),
                new Music("Pional - Tempest"),
                new Music("George Fitzgerald - Frieda"),
                new Music("LK - I Wanna Make Luv 2 U"),
                new Music("Semedo - Make Me Groove"),
                new Music("Boston Bun ft. DVNO - Spread Love (Mercer Remix)"),
                new Music("Just Kiddin - Body Talk (Tommy Mc Remix)"),
                new Music("Junior Sanchez - Strong Enough"),
                new Music("Mercer - Fireworks"),
                new Music("Purple Disco Machine - Dished Male Stripper (Illyus & Barrientos Remix)"),
                new Music("Sterling Void - it’s Alright (Mark Knight Remix)"),
                new Music("Malaa - Cash Money"),
                new Music("Steve Angello & Kryder - Romani"),
                new Music("Bolier & Trobi - In The Water (BLR Festival Remix)"),
                new Music("Moguai & Raumakustik - The Greatest Speech"),
                new Music("Burns - Hands On Me ft. Maluma & Rae Sremmurd (Blonde Remix)"),
                new Music("Freejak & Kelos - My Milkshake (Leftwig & Kody Remix)"),
                new Music("Mercer - Fireworks"),
                new Music("Just Kiddin - Body Talk (Tommy MC Remix)"),
                new Music("Kungs & Stargate GOLDN - Be Right Here"),
                new Music("Alessia Cara - Growing Pains (Dombresky Remix)"),
                new Music("LSD - Thunderclouds (Country Club Martini Crew Remix)"),
                new Music("Tom Staar & Eddie Thoneick - Otherside"),
                new Music("Malaa - Bling Bling (Volac Remix)"),
                new Music("Tom Tyger & Charles B. VCTRY - One Too Many"),
                new Music("Paul Woolford - Hang Up Your Hang Ups (Camelphat Remix)"),
                new Music("Black Coffe & David Guetta - Drive"),
                new Music("Crush Club ft. Supermini - We Dance"),
                new Music("Aevion - Telling Me"),
                new Music("Martin Solveig - My Love"),
                new Music("Samaran - A New Beginning"),
                new Music("Valentino Khan - Feel Your Love"),
                new Music("Fisher - Losing It"),
                new Music("Becky Hill - Sunrise In The East (Kideko Remix)"),
                new Music("Chris Lake & Destructo - Y.O.D.O"),
                new Music("Amersy - Feeling Good"),
                new Music("Klangkuenstler & Davos - We Need Love"),
                new Music("Au/Ra & Camelphat - Panic Room (KDA Remix)"),
                new Music("Junior Jack & Tube & Berger - Esamba 2018"),
                new Music("Becky Hill - Sunrise In The East (Michael Calfan Remix)"),
                new Music("Dj Snake & Niniola - Maradona Riddim"),
                new Music("SG Lewis ft Aluna George - Hurting"),
                new Music("Disclosure - Moonlight"),
                new Music("Cosmo’s Midnight ft Kucka - Ealk With Me (Koa Remix)"),
                new Music("Black Coffee vs David Guetta - Drive"),
                new Music("Burns - Hands On Me (Blonde Remix)"),
                new Music("Shift K3y ft. AME - Entitetry (Weiss Remix)"),
                new Music("Catz ‘N Dogz - Factory Settings"),
                new Music("Toyboy & Robin - Horn It"),
                new Music("Tom Tyger vs Charle B & VCTRY - One Too Many"),
                new Music("Tom Staar & Eddie Thoneick - Otherside"),
                new Music("Mala - Bling Bling (Volac remix)"),
                new Music("Mercer - Fireworks"),
                new Music("Kungs & Stargate GOLDN - Be Right Here"),
                new Music("Alessia Cara - Growing Pains (Dombresky Remix)"),
                new Music("George Fitzgerald - Nobody But You"),
                new Music("Loud Luxury - Body (Dirtycaps Remix)"),
                new Music("Moguai & Aka Aka - Home"),
                new Music("Jacky - Toggles"),
                new Music("Chris Lorenzo & Taiki Nulight - Mind Control (Never Say Never)"),
                new Music("Klang Kuenstler - Block Party"),
                new Music("Format B & Dj PP - In My House"),
                new Music("Petit Biscuit - Waterfall (Karmakid & Fono Remix)"),
                new Music("Tobtok & Adrian Lux - As I Sleep"),
                new Music("Peking Duck - Wasted (SNBRN Remix)"),
                new Music("Pional - Tempest"),
                new Music("Yotto - Chemicals"),
                new Music("Duke Dumont - Inhale (Luke Million Remix)"),
                new Music("Tinish - Struggle (Hawksburn Remix)"),
                new Music("Albin Lee Meldau - The Weight Is Gone (Kc Lights Remix)"),
                new Music("Themba - I Will Do Better"),
                new Music("Fres Rister & Sam Martin ft. Chris Willis - I Want A Miracle (Kc Lights Remix)"),
                new Music("Simon Kidzoo - Cutted Duplate"),
                new Music("Wongo & Billy Kenny - 4My PPL"),
                new Music("Kura - Lambo"),
                new Music("Tube & Berger - International Mother****rs"),
                new Music("Purple Disco Machine - Dished (Male Stripper)"),
                new Music("Peking Duk - Wasted (SNBRN Remix)"),
                new Music("Airwolf - Elevate"),
                new Music("Luboku - Without You"),
                new Music("Pete Heller’s - Big Love (Dr Packer Extended Remix)"),
                new Music("Detroit Swindle - Cut U Loose"),
                new Music("Purple Disco Machine- Dished (Male Stripper Extended)"),
                new Music("Calvin Harris & Dua Lipa - One Kiss (Oliver Heldens Remix)"),
                new Music("Throttle - All In"),
                new Music("Fres Rister & Sam Martin ft Chris Wilis - I Want a Miracle (Kc Lights Remix)"),
                new Music("MEL - Santiago (Alex Metric & Ten Ven Remix)"),
                new Music("U2 - Love Is Bigger Than Anything In It’s Way (Will Clarke Remix)"),
                new Music("Airwolf - Chasing You (Jordan Burns Remix)"),
                new Music("Royksopp - What Else is There (Trentemoller Remix)"),
                new Music("Themba - I Will Do Better"),
                new Music("Pete Heller’s - Big Love (Dr Packer Extended Remix)"),
                new Music("Detroit Swindle - Cut U Loose"),
                new Music("Purple Disco Machine- Dished"),
                new Music("(Male Stripper Extended)"),
                new Music("Calvin Harris & Dua Lipa - One Kiss (Oliver Heldens Remix)"),
                new Music("Throttle - All In"),
                new Music("Fres Rister & Sam Martin ft Chris Wilis - I Want a Miracle (Kc Lights Remix)"),
                new Music("MEL - Santiago (Alex Metric & Ten Ven Remix)"),
                new Music("U2 - Love Is Bigger Than Anything In It’s Way (Will Clarke Remix)"),
                new Music("Airwolf - Chasing You (Jordan Burns Remix)"),
                new Music("Royksopp - What Else is There (Trentemoller Remix)"),
                new Music("Themba - I Will Do Better"),
                new Music("The Magician - Build a Fire"),
                new Music("ID-ID"),
                new Music("Tungevaag & Raaban All For Love (Lucas Sillow Remix)"),
                new Music("Becky Hill - Sunrise In The East (Michael Calfan Remix)"),
                new Music("Tobtok & Adrian Lux - As I Sleep (Bode Remix)"),
                new Music("Kungs & Stargate GLDN - Be Right There"),
                new Music("Mercer - Fireworks"),
                new Music("Ten Ven - Just About"),
                new Music("Young Romantic - Move (Time To Get Loose)"),
                new Music("Valentino Khan - Feel Your Love"),
                new Music("Aevion - Telling Me"),
                new Music("Martin Solveig - My Love"),
                new Music("Dj Snake & Niniola - Maradona Riddim"),
                new Music("Becky Hill - Surise In The East (Michael Calfan Remix)"),
                new Music("Tobtok & Adrian Lux - As I Sleep (Bode Remix)"),
                new Music("Ten Ven - Just About"),
                new Music("Aevion - Telling Me"),
                new Music("Kungs & Stargate GOLDN - Be Right Here"),
                new Music("Valentino Khan - Feel Your Love"),
                new Music("Axwell & Ingrosso ft. Romans - Dancing Alone"),
                new Music("Chris Lake & Destructo & Breach - J.O.D.O Jack (Muzzaik Edit)"),
                new Music("Fisher - Losing It"),
                new Music("Eli Brown - Wait No More"),
                new Music("Au/Ra & Camelphat - Panic Room (Jonas Rathsman Remix)"),
                new Music("Joris Voorn - District Seven"),
                new Music("Crush Club ft. Supermini - We Dance"),
                new Music("Aevion - Telling Me"),
                new Music("Martin Solveig - My Love"),
                new Music("Samaran - A New Beginning"),
                new Music("Valentino Khan - Feel Your Love"),
                new Music("Fisher - Losing It"),
                new Music("Becky Hill - Sunrise In The East (Kideko Remix)"),
                new Music("Chris Lake & Destructo - Y.O.D.O"),
                new Music("Amersy - Feeling Good"),
                new Music("Klangkuenstler & Davos - We Need Love"),
                new Music("Au/Ra & Camelphat - Panic Room (KDA Remix)"),
                new Music("Junior Jack & Tube & Berger - Esamba 2018"),
                new Music("Becky Hill - Sunrise In The East (Michael Calfan Remix)"),
                new Music("Dj Snake & Niniola - Maradona Riddim"),
                new Music("George Fitzgerald - Nobody But You"),
                new Music("Loud Luxury - Body (Dirtycaps Remix)"),
                new Music("Moguai & Aka Aka - Home"),
                new Music("Jacky - Toggles"),
                new Music("Chris Lorenzo & Taiki Nulight - Mind Control (Never Say Never)"),
                new Music("Klang Kuenstler - Block Party"),
                new Music("Format B & Dj PP - In My House"),
                new Music("Petit Biscuit - Waterfall (Karmakid & Fono Remix)"),
                new Music("Tobtok & Adrian Lux - As I Sleep"),
                new Music("Peking Duck - Wasted (SNBRN Remix)"),
                new Music("Pional - Tempest"),
                new Music("Yotto - Chemicals"),
                new Music("George Fitzgerald - Nobody But You"),
                new Music("Loud Luxury - Body (Dirtycaps Remix)"),
                new Music("Moguai & Aka Aka - Home"),
                new Music("Jacky - Toggles"),
                new Music("Chris Lorenzo & Taiki Nulight - Mind Control (Never Say Never)"),
                new Music("Klang Kuenstler - Block Party"),
                new Music("Format B & Dj PP - In My House"),
                new Music("Petit Biscuit - Waterfall (Karmakid & Fono Remix)"),
                new Music("Tobtok & Adrian Lux - As I Sleep"),
                new Music("Peking Duck - Wasted (SNBRN Remix)"),
                new Music("Pional - Tempest"),
                new Music("Yotto - Chemicals"),
                new Music("Disciples - Atheist"),
                new Music("Dusk ft. MO - With You (Eli Brown Remix)"),
                new Music("Friend Within - Lonely"),
                new Music("Gorgon City ft. Kamille & Ghosted - Go Deep (Terrace Remix)"),
                new Music("MEL - Santiago (Alex Metric & Ten Ven Remix)"),
                new Music("Madou - About Tomorrow"),
                new Music("Ferdinand Weber - Nobody (Frank & Friedrich Remix)"),
                new Music("Booka Shade - Confession (Bontan Remix)"),
                new Music("U2 - Love Is Bigger Than Anything In It’s Way (Will Clarke Remix)"),
                new Music("Yotto - Kantsu"),
                new Music("Christoph & Artche - Voice Of Silence"),
                new Music("Pete Heller’s - Big Love (Dr Packer Extended Remix)"),
                new Music("Detroit Swindle - Cut U Loose"),
                new Music("Purple Disco Machine- Dished"),
                new Music("(Male Stripper Extended)"),
                new Music("Calvin Harris & Dua Lipa - One Kiss (Oliver Heldens Remix)"),
                new Music("Throttle - All In"),
                new Music("Fres Rister & Sam Martin ft Chris Wilis - I Want a Miracle (Kc Lights Remix)"),
                new Music("MEL - Santiago (Alex Metric & Ten Ven Remix)"),
                new Music("U2 - Love Is Bigger Than Anything In It’s Way (Will Clarke Remix)"),
                new Music("Airwolf - Chasing You (Jordan Burns Remix)"),
                new Music("Royksopp - What Else is There (Trentemoller Remix)"),
                new Music("Themba - I Will Do Better"),
                new Music("George Fitzgerald - Nobody But You"),
                new Music("Loud Luxury - Body (Dirtycaps Remix)"),
                new Music("Moguai & Aka Aka - Home"),
                new Music("Jacky - Toggles"),
                new Music("Chris Lorenzo & Taiki Nulight - Mind Control (Never Say Never)"),
                new Music("Klang Kuenstler - Block Party"),
                new Music("Format B & Dj PP - In My House"),
                new Music("Petit Biscuit - Waterfall (Karmakid & Fono Remix)"),
                new Music("Tobtok & Adrian Lux - As I Sleep"),
                new Music("Peking Duck - Wasted (SNBRN Remix)"),
                new Music("Pional - Tempest"),
                new Music("Yotto - Chemicals"),
                new Music("Duke Dumont - Inhale (Luke Million Remix)"),
                new Music("Tinish - Struggle (Hawksburn Remix)"),
                new Music("Albin Lee Meldau - The Weight Is Gone (Kc Lights Remix)"),
                new Music("Themba - I Will Do Better"),
                new Music("Fres Rister & Sam Martin ft. Chris Willis - I Want A Miracle (Kc Lights Remix)"),
                new Music("Simon Kidzoo - Cutted Duplate"),
                new Music("Wongo & Billy Kenny - 4My PPL"),
                new Music("Kura - Lambo"),
                new Music("Tube & Berger - International Mother****rs"),
                new Music("Purple Disco Machine - Dished (Male Stripper)"),
                new Music("Peking Duk - Wasted (SNBRN Remix)"),
                new Music("Airwolf - Elevate"),
                new Music("Luboku - Without You"),
                new Music("Disciples - Atheist"),
                new Music("Dusk ft. MO - With You (Eli Brown Remix)"),
                new Music("Friend Within - Lonely"),
                new Music("Gorgon City ft. Kamille & Ghosted"),
                new Music("- Go Deep (Terrace Remix)"),
                new Music("MEL - Santiago (Alex Metric & Ten Ven Remix)"),
                new Music("Madou - About Tomorrow"),
                new Music("Ferdinand Weber - Nobody (Frank & Friedrich Remix)"),
                new Music("Booka Shade - Confession (Bontan Remix)"),
                new Music("U2 - Love Is Bigger Than Anything In It’s Way (Will Clarke Remix)"),
                new Music("Yotto - Kantsu"),
                new Music("Christoph & Artche - Voice Of Silence"),
                new Music("Icarus - Flowers"),
                new Music("Fred Rister & Sam Martin & Chris Willis - I Want a Miracle (Kc Lights Remix)"),
                new Music("Gorgon City ft. Kamille - Go Deep"),
                new Music("Kideko - Good Thing"),
                new Music("Tom Tyger - Infinity"),
                new Music("Dj Koze - Pick Up"),
                new Music("Aevion - Heartbeat"),
                new Music("Loud Luxury ft. Brando - Body (Dirtcaps Remix)"),
                new Music("Polymod - No Other"),
                new Music("Petit Biscuit - Waterfall (Karma Kid & Fono Remix)"),
                new Music("Airwolf - Elevate"),
                new Music("Pional - Tempest"),
                new Music("George Fitzgerald - Frieda"),
                new Music("Pete Heller’s - Big Love (Dr Packer Extended Remix)"),
                new Music("Detroit Swindle - Cut U Loose"),
                new Music("Purple Disco Machine- Dished"),
                new Music("(Male Stripper Extended)"),
                new Music("Calvin Harris & Dua Lipa - One Kiss (Oliver Heldens Remix)"),
                new Music("Throttle - All In"),
                new Music("Fres Rister & Sam Martin ft Chris Wilis - I Want a Miracle (Kc Lights Remix)"),
                new Music("MEL - Santiago (Alex Metric & Ten Ven Remix)"),
                new Music("U2 - Love Is Bigger Than Anything In It’s Way (Will Clarke Remix)"),
                new Music("Airwolf - Chasing You (Jordan Burns Remix)"),
                new Music("Royksopp - What Else is There (Trentemoller Remix)"),
                new Music("Themba - I Will Do Better"),
                new Music("Duke Dumont - Inhale (Luke Million Remix)"),
                new Music("Tinish - Struggle (Hawksburn Remix)"),
                new Music("Albin Lee Meldau - The Weight Is Gone (Kc Lights Remix)"),
                new Music("Themba - I Will Do Better"),
                new Music("Fres Rister & Sam Martin ft. Chris Willis - I Want A Miracle (Kc Lights Remix)"),
                new Music("Simon Kidzoo - Cutted Duplate"),
                new Music("Wongo & Billy Kenny - 4My PPL"),
                new Music("Kura - Lambo"),
                new Music("Tube & Berger - International Mother****rs"),
                new Music("Purple Disco Machine - Dished (Male Stripper)"),
                new Music("Peking Duk - Wasted (SNBRN Remix)"),
                new Music("Airwolf - Elevate"),
                new Music("Luboku - Without You"),
                new Music("George Fitzgerald - Nobody But You"),
                new Music("Loud Luxury - Body (Dirtycaps Remix)"),
                new Music("Moguai & Aka Aka - Home"),
                new Music("Jacky - Toggles"),
                new Music("Chris Lorenzo & Taiki Nulight - Mind Control (Never Say Never)"),
                new Music("Klang Kuenstler - Block Party"),
                new Music("Format B & Dj PP - In My House"),
                new Music("Petit Biscuit - Waterfall (Karmakid & Fono Remix)"),
                new Music("Tobtok & Adrian Lux - As I Sleep"),
                new Music("Peking Duck - Wasted (SNBRN Remix)"),
                new Music("Pional - Tempest"),
                new Music("Yotto - Chemicals"),
                new Music("Atlas Knox - Do It (Mahalo Remix)"),
                new Music("Raiden & Yuri - Always Find You"),
                new Music("CID - Bad For Me"),
                new Music("Tom Tyger & Fader X - Rave Me"),
                new Music("Biscits - On The Floor"),
                new Music("Mahalo - Rhodie"),
                new Music("Illyus & Barrientos - The Wasp"),
                new Music("Klang Kuenstler - Block Party"),
                new Music("Detlef ft Dayae - Deep Dip"),
                new Music("Eats Everything - Burn"),
                new Music("Poolclvb ft. Doolie - Freefall (ZDS Remix)"),
                new Music("Kylie - Dancing (Illyus & Barrientos Remix)"),
                new Music("The Magician - Las Vegas (Vladimir Cauchemar Remix)"),
                new Music("Duke Dumont ft. Ebenezer - Inhale (TCTS Remix)"),
                new Music("Shift K3y - Only You (Funk’d Vip Remix)"),
                new Music("Yolanda Be Cool ft. Kwanzaa Posse - Musika (Flash 89 Remix)"),
                new Music("Jason Chance & Michelle Weeks - Live Your Life"),
                new Music("CID & Sizzy Rocket - Bad For Me"),
                new Music("Tony Calrya & Erick T. - Marimba"),
                new Music("Oliver Heldens - King Kong (HI-LO Mix)"),
                new Music("Gil Sanders & Sonny Noto - Tell Me"),
                new Music("CID - Werk"),
                new Music("Dapayk Solo ft. Komplement - Flood"),
                new Music("Au/Ra & Camelphat - Panic Room"),
                new Music("Yotto - Second Life"),
                new Music("Klang Kurnstler - Block Party"),
                new Music("Detlef ft. Dajae - Deep Dip"),
                new Music("Andy Galea - Yeke Yeke"),
                new Music("Fiaher Oz - Ya Didn’t"),
                new Music("Offaiah - Private Show"),
                new Music("Au/Ra & Camelphat - Panic Room"),
                new Music("Dassent Matter ft. Rush Midnight - Anyone Out There"),
                new Music("Lane 8 ft. Patrick Baker - Skin & Bone (Enamour Remix)"),
                new Music("Yotto - Chemicals"),
                new Music("Bu~Low - Not a Love Song (Jynx Remix)"),
                new Music("George Fitzgerald - Nobody But You"),
                new Music("Loud Luxury - Body (Dirtycaps Remix)"),
                new Music("Moguai & Aka Aka - Home"),
                new Music("Jacky - Toggles"),
                new Music("Chris Lorenzo & Taiki Nulight - Mind Control (Never Say Never)"),
                new Music("Klang Kuenstler - Block Party"),
                new Music("Format B & Dj PP - In My House"),
                new Music("Petit Biscuit - Waterfall (Karmakid & Fono Remix)"),
                new Music("Tobtok & Adrian Lux - As I Sleep"),
                new Music("Peking Duck - Wasted (SNBRN Remix)"),
                new Music("Pional - Tempest"),
                new Music("Yotto - Chemicals"),
                new Music("The Magician - Las Vegas (Vladimir Cauchemar Remix)"),
                new Music("Duke Dumont ft. Ebenezer - Inhale (TCTS Remix)"),
                new Music("Shift K3y - Only You (Funk’d Vip Remix)"),
                new Music("Yolanda Be Cool ft. Kwanzaa Posse - Musika (Flash 89 Remix)"),
                new Music("Jason Chance & Michelle Weeks - Live Your Life"),
                new Music("CID & Sizzy Rocket - Bad For Me"),
                new Music("Tony Calrya & Erick T. - Marimba"),
                new Music("Oliver Heldens - King Kong (HI-LO Mix)"),
                new Music("Gil Sanders & Sonny Noto - Tell Me"),
                new Music("CID - Werk"),
                new Music("Dapayk Solo ft. Komplement - Flood"),
                new Music("Au/Ra & Camelphat - Panic Room"),
                new Music("Yotto - Second Life"),
                new Music("Klang Kurnstler - Block Party"),
                new Music("Detlef ft. Dajae - Deep Dip"),
                new Music("Andy Galea - Yeke Yeke"),
                new Music("Fiaher Oz - Ya Didn’t"),
                new Music("Offaiah - Private Show"),
                new Music("Au/Ra & Camelphat - Panic Room"),
                new Music("Dassent Matter ft. Rush Midnight - Anyone Out There"),
                new Music("Lane 8 ft. Patrick Baker - Skin & Bone (Enamour Remix)"),
                new Music("Yotto - Chemicals"),
                new Music("Bu~Low - Not a Love Song (Jynx Remix)"),
                new Music("The Magician - Las Vegas (Vladimir Cauchemar Remix)"),
                new Music("Duke Dumont ft. Ebenezer - Inhale (TCTS Remix)"),
                new Music("Shift K3y - Only You (Funk’d Vip Remix)"),
                new Music("Yolanda Be Cool ft. Kwanzaa Posse - Musika (Flash 89 Remix)"),
                new Music("Jason Chance & Michelle Weeks - Live Your Life"),
                new Music("CID & Sizzy Rocket - Bad For Me"),
                new Music("Tony Calrya & Erick T. - Marimba"),
                new Music("Oliver Heldens - King Kong (HI-LO Mix)"),
                new Music("Gil Sanders & Sonny Noto - Tell Me"),
                new Music("CID - Werk"),
                new Music("Dapayk Solo ft. Komplement - Flood"),
                new Music("Au/Ra & Camelphat - Panic Room"),
                new Music("Yotto - Second Life"),
                new Music("Atlas Knox - Do It (Mahalo Remix)"),
                new Music("Raiden & Yuri - Always Find You"),
                new Music("CID - Bad For Me"),
                new Music("Tom Tyger & Fader X - Rave Me"),
                new Music("Biscits - On The Floor"),
                new Music("Mahalo - Rhodie"),
                new Music("Illyus & Barrientos - The Wasp"),
                new Music("Klang Kuenstler - Block Party"),
                new Music("Detlef ft Dayae - Deep Dip"),
                new Music("Eats Everything - Burn"),
                new Music("Poolclvb ft. Doolie - Freefall (ZDS Remix)"),
                new Music("Kylie - Dancing (Illyus & Barrientos Remix)"),
                new Music("Klang Kurnstler - Block Party"),
                new Music("Detlef ft. Dajae - Deep Dip"),
                new Music("Andy Galea - Yeke Yeke"),
                new Music("Fiaher Oz - Ya Didn’t"),
                new Music("Offaiah - Private Show"),
                new Music("Au/Ra & Camelphat - Panic Room"),
                new Music("Dassent Matter ft. Rush Midnight - Anyone Out There"),
                new Music("Lane 8 ft. Patrick Baker - Skin & Bone (Enamour Remix)"),
                new Music("Yotto - Chemicals"),
                new Music("Bu~Low - Not a Love Song (Jynx Remix)"),
                new Music("The Magician - Las Vegas (Vladimir Cauchemar Remix)"),
                new Music("Duke Dumont ft. Ebenezer - Inhale (TCTS Remix)"),
                new Music("Shift K3y - Only You (Funk’d Vip Remix)"),
                new Music("Yolanda Be Cool ft. Kwanzaa Posse - Musika (Flash 89 Remix)"),
                new Music("Jason Chance & Michelle Weeks - Live Your Life"),
                new Music("CID & Sizzy Rocket - Bad For Me"),
                new Music("Tony Calrya & Erick T. - Marimba"),
                new Music("Oliver Heldens - King Kong (HI-LO Mix)"),
                new Music("Gil Sanders & Sonny Noto - Tell Me"),
                new Music("CID - Werk"),
                new Music("Dapayk Solo ft. Komplement - Flood"),
                new Music("Au/Ra & Camelphat - Panic Room"),
                new Music("Yotto - Second Life"),
                new Music("Metrush - Upside Down"),
                new Music("Mahalo ft. Kadiri James - Here With Me"),
                new Music("CID - Bad For Me"),
                new Music("Michael Calfan - On You (TCTS Dub)"),
                new Music("Claptone ft. Ben Duffy - In The Night (Illyus & Barrientos Remix)"),
                new Music("Gorgon City -Motorola"),
                new Music("Mihalis Safras - Love Away"),
                new Music("Chappell Roan - Good Hurt (Siege Remix)"),
                new Music("The Knocks ft Foster The People - Ride Or Die (Vip Remix)"),
                new Music("CID - Werk"),
                new Music("Chocolate Puma ft. Chateau - Gotta Get Away"),
                new Music("Yolanda Be Cool ft. Kwanzaa Posse - Musika"),
                new Music("Dave Sol & Unomas - Stories"),
                new Music("Disciples - 48HRS"),
                new Music("Gorgon City - Motorola"),
                new Music("Marcus Schossow - White Lies"),
                new Music("Au/Ra & Camelphat - Panic Room"),
                new Music("Simon Kidzoo - KITT"),
                new Music("Fatboy Slim - Right Here Right Now (Camelphat Remix)"),
                new Music("Rayven & Valexx - 2Nite"),
                new Music("Dj Snake - Magenta Riddim (Lumberjack Remix)"),
                new Music("Chris Lake & Alexis Roberts - Turn Off The Lights"),
                new Music("ZDS - Sweat"),
                new Music("Dirty South - If itt All Stops"),
                new Music("Branch & Broo - Yours (Mike Mago Remix)"),
                new Music("SG Lewis - Aura"),
                new Music("Pretty Pink - Trick"),
                new Music("Eli Brown - The Guru"),
                new Music("Offaiah - Private Show"),
                new Music("Dirty South & Eden Prince - Belive"),
                new Music("Teser - Duo"),
                new Music("Don Diablo - ID"),
                new Music("Sander Kleinenberg ft. Feorge Mcrae - Colours In The Sun"),
                new Music("Sonin ft. Swedish Red Elephant - All Of My Teengae Crime"),
                new Music("Apres - Til Your Love"),
                new Music("Fraky Rizardo - Call Upon Me"),
                new Music("Nora En Pure - Sphinx"),
                new Music("Gorgon City - Motorola"),
                new Music("Claptone - In The Night (Illyus & Barrientos Remix)"),
                new Music("Simon Kidzoo - KITT"),
                new Music("Fisher - Crowd Control"),
                new Music("SG Lewis - Aura (Mele Remix)"),
                new Music("Jax Jones ft. Ina Wroldsen - Breathe (Boston Bun Remix)"),
                new Music("Marcus Schossow - White Lies"),
                new Music("Chez Moon - Close To Me (Mahalo Remix)"),
                new Music("Zonderling ft. Kye Sones - Nightcall"),
                new Music("Disciples - 48HRS"),
                new Music("Au/Ra & Camelphat - Panic Room"),
                new Music("Yotto - Second Life"),
                new Music("Icarus - Love Has Come Around"),
                new Music("GTA & Dillon Francis & Wax Motif -ft Anna Lunoe - I Can’t Hold On"),
                new Music("Just Kiddin - Indiana"),
                new Music("Sander Kleinenber ft. George McCrae - Colours In The Sun"),
                new Music("Shift K3Y - Only You (Offaiah Remix)"),
                new Music("Illius & Barrientos - So Serious"),
                new Music("Nicky Romero & Florian Picasso - Only For Ur Love (Tom Tyger Remix)"),
                new Music("Offaiah - Private Show"),
                new Music("Fatboy Slim - Weapon Of Choice (Set Mo Remix)"),
                new Music("Apres - Til Your Love"),
                new Music("Sonin ft Swedish Red Elephant - All Of My Tenage Crime"),
                new Music("Franky Rizardo - Call Upon Me"),
                new Music("Dave Sol & Unomas - Stories"),
                new Music("Disciples - 48HRS"),
                new Music("Gorgon City - Motorola"),
                new Music("Marcus Schossow - White Lies"),
                new Music("Au/Ra & Camelphat - Panic Room"),
                new Music("Simon Kidzoo - KITT"),
                new Music("Fatboy Slim - Right Here Right Now (Camelphat Remix)"),
                new Music("Rayven & Valexx - 2Nite"),
                new Music("Dj Snake - Magenta Riddim (Lumberjack Remix)"),
                new Music("Chris Lake & Alexis Roberts - Turn Off The Lights"),
                new Music("ZDS - Sweat"),
                new Music("Dirty South - If itt All Stops"),
                new Music("Branch & Broo - Yours (Mike Mago Remix)"),
                new Music("The Knocks Captain Cuts - House Party"),
                new Music("Keljet ft. Dam - Blue"),
                new Music("Parx - Lola’s Theme"),
                new Music("Mercer & Ron Caroll - Satisfy"),
                new Music("Illyus & Barrientos - So Serious"),
                new Music("Tiga - Woke (Andrea Oliva Remix)"),
                new Music("Fisher - Stop It"),
                new Music("Vladimir Cauchemar - Aulos"),
                new Music("EDX - Jaded"),
                new Music("Keljet ft Dam. - Blue (Vip Mix)"),
                new Music("Wongo San Mei - Paradise (Yolanda Be Cool Malibu’s Mix)"),
                new Music("Dark Science - Prophecy"),
                new Music("Claptone - In The Night"),
                new Music("Dave Winnel - WYDTM"),
                new Music("Illius & Barrientos - So Serious"),
                new Music("Leandro Da Silva - So Crazy"),
                new Music("Parx - Lola’s Theme"),
                new Music("Mercer ft. Ron Carroll - Satisfy"),
                new Music("Tiga - Woke (Andrea Oliva Remix)"),
                new Music("Sebjak & David Pietras - Soleil"),
                new Music("A~DA - Fishmarket"),
                new Music("Joseph Asworth - Carmine"),
                new Music("SG Lewis - Aura"),
                new Music("Pretty Pink - Trick"),
                new Music("Eli Brown - The Guru"),
                new Music("Offaiah - Private Show"),
                new Music("Dirty South & Eden Prince - Belive"),
                new Music("Teser - Duo"),
                new Music("Don Diablo - ID"),
                new Music("Sander Kleinenberg ft. Feorge Mcrae - Colours In The Sun"),
                new Music("Sonin ft. Swedish Red Elephant - All Of My Teengae Crime"),
                new Music("Apres - Til Your Love"),
                new Music("Fraky Rizardo - Call Upon Me"),
                new Music("Nora En Pure - Sphinx"),
                new Music("Icarus - Love Has Come Around"),
                new Music("GTA & Dillon Francis & Wax Motif -ft Anna Lunoe - I Can’t Hold On"),
                new Music("Just Kiddin - Indiana"),
                new Music("Sander Kleinenber ft. George McCrae - Colours In The Sun"),
                new Music("Shift K3Y - Only You (Offaiah Remix)"),
                new Music("Illius & Barrientos - So Serious"),
                new Music("Nicky Romero & Florian Picasso - Only For Ur Love (Tom Tyger Remix)"),
                new Music("Offaiah - Private Show"),
                new Music("Fatboy Slim - Weapon Of Choice (Set Mo Remix)"),
                new Music("Apres - Til Your Love"),
                new Music("Sonin ft Swedish Red Elephant - All Of My Tenage Crime"),
                new Music("Franky Rizardo - Call Upon Me"),
                new Music("Avicii - Lonely Together (Jaded Remix)"),
                new Music("Adrian Lux & Savage - Teust Me (CID Remix)"),
                new Music("Ed Sheeran - Don't (Don Diablo Remix)"),
                new Music("Chris Lake & Chris Lorenzo - Nothing Better"),
                new Music("Just Kiddin - More To Life (AXRG)"),
                new Music("Martin Solveig ft. Alma - All Star (Mercer Remix)"),
                new Music("L'Tric - This Feeling (Kryder Remix)"),
                new Music("Francies Mercier - Shakin"),
                new Music("Sovth - Sovereign"),
                new Music("Gorgon City - Primal Call"),
                new Music("Kc Lights - Sunshine"),
                new Music("The XX - On Hold (Jamie XX Remix)"),
                new Music("MK - 17"),
                new Music("The Knocks Captain Cuts - House Party"),
                new Music("Keljet ft. Dam - Blue"),
                new Music("Parx - Lola’s Theme"),
                new Music("Mercer & Ron Caroll - Satisfy"),
                new Music("Illyus & Barrientos - So Serious"),
                new Music("Tiga - Woke (Andrea Oliva Remix)"),
                new Music("Fisher - Stop It"),
                new Music("Vladimir Cauchemar - Aulos"),
                new Music("EDX - Jaded"),
                new Music("Keljet ft Dam. - Blue (Vip Mix)"),
                new Music("Wongo San Mei - Paradise (Yolanda Be Cool Malibu’s Mix)"),
                new Music("Dark Science - Prophecy"),
                new Music("The Knocks Captain Cuts - House Party"),
                new Music("Keljet ft. Dam - Blue"),
                new Music("Parx - Lola’s Theme"),
                new Music("Mercer & Ron Caroll - Satisfy"),
                new Music("Illyus & Barrientos - So Serious"),
                new Music("Tiga - Woke (Andrea Oliva Remix)"),
                new Music("Fisher - Stop It"),
                new Music("Vladimir Cauchemar - Aulos"),
                new Music("EDX - Jaded"),
                new Music("Keljet ft Dam. - Blue (Vip Mix)"),
                new Music("Wongo San Mei - Paradise (Yolanda Be Cool Malibu’s Mix)"),
                new Music("Dark Science - Prophecy"),
                new Music("Claptone - In The Night"),
                new Music("Dave Winnel - WYDTM"),
                new Music("Illius & Barrientos - So Serious"),
                new Music("Leandro Da Silva - So Crazy"),
                new Music("Parx - Lola’s Theme"),
                new Music("Mercer ft. Ron Carroll - Satisfy"),
                new Music("Tiga - Woke (Andrea Oliva Remix)"),
                new Music("Sebjak & David Pietras - Soleil"),
                new Music("A~DA - Fishmarket"),
                new Music("Joseph Asworth - Carmine"),
                new Music("The Knocks Captain Cuts - House Party"),
                new Music("Keljet ft. Dam - Blue"),
                new Music("Parx - Lola’s Theme"),
                new Music("Mercer & Ron Caroll - Satisfy"),
                new Music("Illyus & Barrientos - So Serious"),
                new Music("Tiga - Woke (Andrea Oliva Remix)"),
                new Music("Fisher - Stop It"),
                new Music("Vladimir Cauchemar - Aulos"),
                new Music("EDX - Jaded"),
                new Music("Keljet ft Dam. - Blue (Vip Mix)"),
                new Music("Wongo San Mei - Paradise (Yolanda Be Cool Malibu’s Mix)"),
                new Music("Dark Science - Prophecy"),
                new Music("One Republic - If i lose myself (Muzzaik Edit)"),
                new Music("Muzzaik - Freedom (Prok & Fitch Remix)"),
                new Music("Calvin Harris - Thinking About You (Muzzaik Edit)"),
                new Music("Seinabo Sey - Hard Time (Muzzaik Remix)"),
                new Music("M83 - Midnight City (Muzzaik Edit)"),
                new Music("Take It (Muzzaik Remix)"),
                new Music("Jeremy Duplax & Daniel Delay - Bodyshine"),
                new Music("Ron Caroll - Bump To Dis (Muzzaik Remix)"),
                new Music("Muzzaik - Forget"),
                new Music("Muzzaik & StadiumX - So Much Love"),
                new Music("Muzzaik & StadiumX - Aria"),
                new Music("Agebeat & Kovary - Illusion (Muzzaik & Dave Martin Remix)"),
                new Music("Moonbotica ft. Nneka - Do Not Do Me"),
                new Music("Keljet ft. David Dam - Blue"),
                new Music("The Knocks Captain Cuts - House Party"),
                new Music("Wongo ft. San Mei - Paradise (Yolanda Be Cool’s Malibu Mix)"),
                new Music("Mercer ft. Ron Carroll - Satisfy"),
                new Music("Bruno Mars - Versace On The Floor (CID Remix)"),
                new Music("Tiga - Woke (Andrea Olivia Remix)"),
                new Music("Cabarza - Want You (Yousef Circus Rework)"),
                new Music("Gorgon City - Grooves On The Vinyl"),
                new Music("Vladimir Cauchemar - Aulos"),
                new Music("Green Velvet & Riva Starr - Keep Pushing (Harder)"),
                new Music("Classic Track"),
                new Music("Hardsoul & Julien Jabre - Swimming Religion (Martin Ten Velden Edit)"),
                new Music("Muzzaikft. Zaida -WorkIt (PP Remix)"),
                new Music("OneRepublic - If i LoseMyself (Muzzaik Edit)"),
                new Music("Jesse Rose - TakeIt (Muzzaik Edit)"),
                new Music("Sultan& Tommyboy - B With U (MuzzaikRemix)"),
                new Music("SelenaGomez - Same Old Love (MuzzaikRemix)"),
                new Music("James Blunt& Robin Schulz - Ok (StadiumX Remix)"),
                new Music("Muzzaik& StadiumX - SoMuch Love"),
                new Music("StadiumX &Muzzaik - LastNight a Dj SavedMy Life"),
                new Music("Ultra Nate - Free (MuzzaikRemix)"),
                new Music("Muzzaik - S.O.S (S-man Revision)"),
                new Music("Muzzaik - Back &Forth"),
                new Music("PerQX& Elias Bravo - TakeMe Home (MuzzaikRemix)"),
                new Music("Avicii - Lonely Together (Jaded Remix)"),
                new Music("Adrian Lux & Savage - Teust Me (CID Remix)"),
                new Music("Ed Sheeran - Don't (Don Diablo Remix)"),
                new Music("Chris Lake & Chris Lorenzo - Nothing Better"),
                new Music("Just Kiddin - More To Life (AXRG)"),
                new Music("Martin Solveig ft. Alma - All Star (Mercer Remix)"),
                new Music("L'Tric - This Feeling (Kryder Remix)"),
                new Music("Francies Mercier - Shakin"),
                new Music("Sovth - Sovereign"),
                new Music("Gorgon City - Primal Call"),
                new Music("Kc Lights - Sunshine"),
                new Music("The XX - On Hold (Jamie XX Remix)"),
                new Music("MK - 17"),
                new Music("Moonbotica ft. Nneka - So not Do me"),
                new Music("Cassian - Know You Well"),
                new Music("Catchment & Remoda - Cured"),
                new Music("Dark Science - Prophecy"),
                new Music("Waze & Odyssey - All Of Us"),
                new Music("Tennan - Everyday (Detlef Remix)"),
                new Music("Green Velvet & Riva Starr - Keep Pushin (Harder)"),
                new Music("Tiga - Woke (Martin Solveig Remix)"),
                new Music("Vladimir Cauchemar - Aulos"),
                new Music("EDX - All I Know"),
                new Music("Tom Tyger & Raiden - C'est La Vibe"),
                new Music("Rihanna - Consideration (Dirty South Remix)"),
                new Music("Gorgon City - Grooves On The Vinyl"),
                new Music("Motez&Cleopatra - The Future"),
                new Music("Alex Adair .- Casual (Thomas Gold Remix)"),
                new Music("Chris Lake & Chris Lorenzo - NothingBetter"),
                new Music("Katrella - FindOurWay"),
                new Music("La Fuente - LIT"),
                new Music("Hiisak& Marco Carpentieri - GottaSay"),
                new Music("Go Freak - PutIt Down (KormakRemix)"),
                new Music("Mark Knight& Ben Remember - LetMe Go"),
                new Music("Detlef - Jaydee"),
                new Music("Gorillaz - Busted&Blue (YottoRemix)"),
                new Music("Illius&Barrientos - California"),
                new Music("Cristophft. Forrest - The Sign"),
                new Music("Camelphat - Cola"),
                new Music("Eric Prydz - Pjanoo"),
                new Music("Dombresky& Tony Romera - GirlsNight Out"),
                new Music("Gorgon City - GroovesOn The Vinyl"),
                new Music("Fisher - Stop It"),
                new Music("PatrickTopping - Be Sharp SayNowt"),
                new Music("Gorgon City - PrimalCall"),
                new Music("Mark Knight&Tuff London - Jus' Come"),
                new Music("Eli Brown - Sumatra"),
                new Music("Klosman&Nico De Andrea - PorqueMeVoy"),
                new Music("Dick Johnson - Senegal"),
                new Music("Max Wings - Gravedance"),
                new Music("CooperatedSouls - BornToRage (New ID Edit)"),
                new Music("Tinilicker - Motion"),
                new Music("Unknown - Otic"),
                new Music("Jesse Rose - InMy Mind (Amtrac' Voyage Mix)"),
                new Music("Catchment & Remoda - Cured"),
                new Music("Dark Science - Prophecy"),
                new Music("Dan Aux - The Spot"),
                new Music("Green Velvet & Tiva Staar - Keep Pushing (Harder)"),
                new Music("Vladimir Cauchemar - Aulos"),
                new Music("Eli Brown - Sumatra"),
                new Music("Tom Tyger & Vyktor Nova - Move Your Feet"),
                new Music("Havoc & Lawn - Windmills"),
                new Music("Adrien Rux & Bedmar & David Tuck & Kuaigon - Set Me Free"),
                new Music("EDX - All I Know"),
                new Music("Gorgon City - Grooves OnThe Vinyl"),
                new Music("Vladimir Cauchemar - Aulos"),
                new Music("Motez&Cleopatra - The Future"),
                new Music("Alex Adair .- Casual (Thomas Gold Remix)"),
                new Music("Chris Lake & Chris Lorenzo - NothingBetter"),
                new Music("Katrella - FindOurWay"),
                new Music("La Fuente - LIT"),
                new Music("Hiisak& Marco Carpentieri - GottaSay"),
                new Music("Go Freak - PutIt Down (KormakRemix)"),
                new Music("Mark Knight& Ben Remember - LetMe Go"),
                new Music("Detlef - Jaydee"),
                new Music("Gorillaz - Busted&Blue (YottoRemix)"),
                new Music("Illius&Barrientos - California"),
                new Music("Cristophft. Forrest - The Sign"),
                new Music("Camelphat - Cola"),
                new Music("Eric Prydz - Pjanoo"),
                new Music("Dombresky& Tony Romera - GirlsNight Out"),
                new Music("Gorgon City - GroovesOn The Vinyl"),
                new Music("Fisher - Stop It"),
                new Music("PatrickTopping - Be Sharp SayNowt"),
                new Music("Gorgon City - PrimalCall"),
                new Music("Mark Knight&Tuff London - Jus' Come"),
                new Music("Eli Brown - Sumatra"),
                new Music("Klosman&Nico De Andrea - PorqueMeVoy"),
                new Music("Dick Johnson - Senegal"),
                new Music("Max Wings - Gravedance"),
                new Music("CooperatedSouls - BornToRage (New ID Edit)"),
                new Music("Tinilicker - Motion"),
                new Music("Unknown - Otic"),
                new Music("Jesse Rose - InMy Mind (Amtrac' Voyage Mix)"),
                new Music("Avicii - Lonely Together (Jaded Remix)"),
                new Music("Adrian Lux & Savage - Teust Me (CID Remix)"),
                new Music("Ed Sheeran - Don't (Don Diablo Remix)"),
                new Music("Chris Lake & Chris Lorenzo - Nothing Better"),
                new Music("Just Kiddin - More To Life (AXRG)"),
                new Music("Martin Solveig ft. Alma - All Star (Mercer Remix)"),
                new Music("L'Tric - This Feeling (Kryder Remix)"),
                new Music("Francies Mercier - Shakin"),
                new Music("Sovth - Sovereign"),
                new Music("Gorgon City - Primal Call"),
                new Music("Kc Lights - Sunshine"),
                new Music("The XX - On Hold (Jamie XX Remix)"),
                new Music("MK - 17"),
                new Music("Pnau- Go Bang (Flash89 Extended Remix)"),
                new Music("Gorgon City - Grooves On The Vinyl"),
                new Music("Mark Knight & Tuff London - Jus' Come"),
                new Music("Tom Tyger & Vyktor Nova - Move Your Feet"),
                new Music("Bruno Mars - Versace On The Floor (CID Remix)"),
                new Music("Galantis x Throttle - Tell Me You Love (Toby Green Remix)"),
                new Music("Mercer - Move"),
                new Music("Damien N-Drix - Inkali"),
                new Music("Eli Brown - Sumatra"),
                new Music("EDX - All I Know"),
                new Music("Dark Science - Prophecy"),
                new Music("Gorgon City - Primal Call"),
                new Music("Eli & Fur - Around You (Oc & Verde Remix)"),
                new Music("Gershon Jackson - Huggin A Luvin (Chocolate Puma Remix)"),
                new Music("James Curd - PleaseDon't Play (CamelphatRemix)"),
                new Music("DepecheMode - GoingBackwards (ClaptoneRemix)"),
                new Music("Mark Knightft. RaggaTwins - MoveOn"),
                new Music("Marcus Schossow - Rumble"),
                new Music("Bakermatft. Kiesza - Don'tWantYou Back (Mat Joe Remix)"),
                new Music("Go Freek - PutIt Down"),
                new Music("Chris Lake - GiveHer Right Back"),
                new Music("Sinden - Bruk Out"),
                new Music("Ibranovski - NoseCandy"),
                new Music("Simon Kidzoo - Pop The Trunk (SJ & RM Remix)"),
                new Music("DaveWinnel - Kazoo"),
                new Music("SanderKleinenberg& Boris Smith - Trouble"),
                new Music("Jean Baccarezza - DoItLikeIt"),
                new Music("Mark Knight& Ben Remember - LetMe Go"),
                new Music("Maya Jane Coles - Go On And MakeItThrough"),
                new Music("Madou - NowhereElse"),
                new Music("Sentre - LostIn The Moment"),
                new Music("The Blaze - Territory"),
                new Music("Cristophft. JemCooke - Feel"),
                new Music("Secondcity - Kwelanga"),
                new Music("Camelphat - Gypsy King"),
                new Music("Dj. S.K.T - Jack The Jack"),
                new Music("Prok&Fitch - Nodding Dog"),
                new Music("Biscits - Real Low (BillyKennyRemix)"),
                new Music("Eli Brown - Got The Power"),
                new Music("DukeDumont&Gorgon City - Real Life (SolardoRemix)"),
                new Music("Audion - MouthToMouth (Dense&PikaRemix)"),
                new Music("Boston Bun - MissingYou"),
                new Music("Avicii - Lonely Together (Jaded Remix)"),
                new Music("Adrian Lux & Savage - Teust Me (CID Remix)"),
                new Music("Ed Sheeran - Don't (Don Diablo Remix)"),
                new Music("Chris Lake & Chris Lorenzo - Nothing Better"),
                new Music("Just Kiddin - More To Life (AXRG)"),
                new Music("Martin Solveig ft. Alma - All Star (Mercer Remix)"),
                new Music("L'Tric - This Feeling (Kryder Remix)"),
                new Music("Francies Mercier - Shakin"),
                new Music("Sovth - Sovereign"),
                new Music("Gorgon City - Primal Call"),
                new Music("Kc Lights - Sunshine"),
                new Music("The XX - On Hold (Jamie XX Remix)"),
                new Music("MK - 17"),
                new Music("Icarus - No Sleep"),
                new Music("Dombresky & Tony Romera - Girls Night Out"),
                new Music("Patrick Topping - Be Sharp Say Nowt"),
                new Music("Blaze - Lovelee Dae (Kevin Hedge)"),
                new Music("Fisher - Stop it"),
                new Music("Dick Johnson - Senegal"),
                new Music("Eli Brown - Sumatra"),
                new Music("Kc Flightt & Funky Junction- Voices (Fata Morgana Remix)"),
                new Music("Klosman & Nico De Andrea - Porque Me Voy"),
                new Music("Gorgon City - Primal Call"),
                new Music("The XX - On Hold (Jamie XX Remix)"),
                new Music("ID - Otic"),
                new Music("Tchami - Adieu"),
                new Music("MK- 17"),
                new Music("Gorgon City - Primal Call"),
                new Music("Motez - The Future (Purple Disco Machine Remix)"),
                new Music("Martin Solveig ft. Alma - All Star (Mercer Remix)"),
                new Music("Lane 8 - March Of the Forest"),
                new Music("Motez&Cleopatra - The Future"),
                new Music("Alex Adair .- Casual (Thomas Gold Remix)"),
                new Music("Chris Lake & Chris Lorenzo - NothingBetter"),
                new Music("Katrella - FindOurWay"),
                new Music("La Fuente - LIT"),
                new Music("Hiisak& Marco Carpentieri - GottaSay"),
                new Music("Go Freak - PutIt Down (KormakRemix)"),
                new Music("Mark Knight& Ben Remember - LetMe Go"),
                new Music("Detlef - Jaydee"),
                new Music("Gorillaz - Busted&Blue (YottoRemix)"),
                new Music("Illius&Barrientos - California"),
                new Music("Cristophft. Forrest - The Sign"),
                new Music("Camelphat - Cola"),
                new Music("Eric Prydz - Pjanoo"),
                new Music("Avicii& Rita Ora - LonelyTogether"),
                new Music("Alex Adair - Casual (Thomas Gold Remix)"),
                new Music("Martin Solveigft. Alma - AllStars (ApexapeRemix)"),
                new Music("DukeDumont&Gorgon City ft. Naations - Real Life"),
                new Music("CeeLoGreen&CID - Believer (MednasRemix)"),
                new Music("KcLightsft. Rae Hall - Sundown"),
                new Music("Robin Schulzft. James Blunt - Ok (OfenbachRemix)"),
                new Music("Chris Lake & Chris Lorenzo - NothingBetter"),
                new Music("VintageCulture& Bruno Be - Human"),
                new Music("Rationale - Loving Life (FrankyRizardoRemix)"),
                new Music("Dj S.K.T - Must Be A Reason"),
                new Music("Boston Bun - MissingYou"),
                new Music("Saint WKND - MakeYouMine (KcLightsRemix)"),
                new Music("Rudimentalft. James Arthur - Sun ComesUp (OffaiahRemix)"),
                new Music("Aevion - Summer"),
                new Music("Gorgon City - Primal Call"),
                new Music("Kink - Perth"),
                new Music("Mella Dee - Techno Disco Tool"),
                new Music("Dombresky & Samaran - Call 909"),
                new Music("Fisher - Stop It"),
                new Music("Dick Johnson - Senegal"),
                new Music("Kideko & Tinie Tempah & Becky G - Dum Dum (Yousef Circus Rework)"),
                new Music("Klosman & Nico De Andrea - Porque Me Voy"),
                new Music("Tinlicker - Motion"),
                new Music("ID - Otic"),
                new Music("Going Deeper & Deep Matter - Y Don't U"),
                new Music("Martin Solveig ft. Tkay Maidza - Do It Right (Kc Lights)"),
                new Music("The XX - On Hold (Jamie XX Remix)"),
                new Music("Tchami & Malaa - The Sermon"),
                new Music("Fisher - Stop It"),
                new Music("Dick Johnson - Senegal"),
                new Music("Klosman & Nico De Andrea - Porque Me Voy"),
                new Music("Will K - Sour Milk"),
                new Music("Billy Kenny - This Report"),
                new Music("Mella Dee - Techno"),
                new Music("Disco Tool"),
                new Music("Dombresky & Samaran - Call 909"),
                new Music("Kink - Perth"),
                new Music("Unknown - Otic"),
                new Music("Motez&Cleopatra - The Future"),
                new Music("Alex Adair .- Casual (Thomas Gold Remix)"),
                new Music("Chris Lake & Chris Lorenzo - NothingBetter"),
                new Music("Mark Knight& Ben Remember - LetMe Go"),
                new Music("Camelphat – Cola"),
                new Music("Sam Supplier - Night & Day (Illyus & Barrientos Remix)"),
                new Music("Martin Solveig - Do It Right (Kc Lights Remix)"),
                new Music("Tim Baresko, Room 303 - Marilyn Monroe (Nathan Boraton Remix)"),
                new Music("The XX - On Hold (Jamie XX Remix)"),
                new Music("Mella Dee - Techno Disco Tool"),
                new Music("Will K - Sour Milk"),
                new Music("Dombresky & Samaran - Call 909"),
                new Music("Kink - Perth"),
                new Music("Andhim - Amene"),
                new Music("Gorgon City - Primal Call"),
                new Music("Lane 8 ft Polica - No Captain"),
                new Music("Motez - The Future (KcLightsRemix)"),
                new Music("Cliq - Weavey"),
                new Music("The XX - On Hold (Jamies XX Remix)"),
                new Music("Samuel Dan&Fancy INC - Black Box"),
                new Music("Carsi B - BodakYellow (CID Remix)"),
                new Music("Martin Solveig - Do It Right (Kc Lights Remix)"),
                new Music("MK - 17 (In The Air Dub)"),
                new Music("The XX - On Hold (Jamie XX Remix)"),
                new Music("Kink - Perth"),
                new Music("Dombresky & Samaran - Call 909"),
                new Music("King Arthur - Laidback"),
                new Music("Green Velvet & Shiba San - Chance"),
                new Music("Martin Solveig - Do It Right (Marc Spence Remix)"),
                new Music("Aevion - Best In You"),
                new Music("Sovth - Boriquas"),
                new Music("Robosonic ft. Stag - Wurd (Camelphat Remix)"),
                new Music("Muzzaik - Closer (Spinnin)"),
                new Music("Muzzaik - Paradise"),
                new Music("Yves Larock - Push it (Muzzaik Remix)"),
                new Music("Muzzaik & Stadium-X - So Much Love"),
                new Music("Selena Gomez - Same Old Love (Muzzaik Remix)"),
                new Music("Stadium-X & Muzzaik - Last Night a Dj Saved My Life"),
                new Music("Robin Schulz ft. Akon - Heatwave - (Muzzaik Remix)"),
                new Music("Sam Feldt & Deepend ft. Temuu - Runaways (Muzzaik Remix)"),
                new Music("Stadium-X - TWTD (Metrush Edit)"),
                new Music("Stadium-X ft. Bishop - The Fall"),
                new Music("Muzzaik - Better Days"),
                new Music("Ron Carroll - Bump Do This (Muzzaik Edit)"),
                new Music("Muzzaik - Face It"),
                new Music("Yves Larock - Zoo (Muzzaik Remix)"),
                new Music("Sebastian Drums - French Rules (Muzzaik Remix)"),
                new Music("Motez - The Future (Kc Lights Remix)"),
                new Music("Cliq - Weavey"),
                new Music("The XX - On Hold (Jamies XX Remix)"),
                new Music("Samuel Dan & Fancy INC - Black Box"),
                new Music("Carsi B - Bodak Yellow (CID Remix)"),
                new Music("Format:B - The Scoop"),
                new Music("Claude Vonstroke - Barump (Billy Kenny Remix)"),
                new Music("Dombresky & Samaran - Call 909"),
                new Music("Gorgon City - Primal Call"),
                new Music("SOVTH - Sovereign"),
                new Music("MK - 17 (Camelphat Remix)"),
                new Music("Lane 8 - March Of The Forest Cat"),
                new Music("Gershon Jackson - Huggin A Luvin (Chocolate Puma Remix)"),
                new Music("James Curd - PleaseDon't Play (CamelphatRemix)"),
                new Music("DepecheMode - GoingBackwards (ClaptoneRemix)"),
                new Music("Mark Knightft. RaggaTwins - MoveOn"),
                new Music("Marcus Schossow - Rumble"),
                new Music("Bakermatft. Kiesza - Don'tWantYou Back (Mat Joe Remix)"),
                new Music("Go Freek - PutIt Down"),
                new Music("Chris Lake - GiveHer Right Back"),
                new Music("Sinden - Bruk Out"),
                new Music("Ibranovski - NoseCandy"),
                new Music("Simon Kidzoo - Pop The Trunk (SJ & RM Remix)"),
                new Music("DaveWinnel - Kazoo"),
                new Music("SanderKleinenberg& Boris Smith - Trouble"),
                new Music("Jean Baccarezza - DoItLikeIt"),
                new Music("Mark Knight& Ben Remember - LetMe Go"),
                new Music("Maya Jane Coles - Go On And MakeItThrough"),
                new Music("Motez&Cleopatra - The Future"),
                new Music("Alex Adair .- Casual (Thomas Gold Remix)"),
                new Music("Chris Lake & Chris Lorenzo - NothingBetter"),
                new Music("Katrella - FindOurWay"),
                new Music("La Fuente - LIT"),
                new Music("Hiisak& Marco Carpentieri - GottaSay"),
                new Music("Go Freak - PutIt Down (KormakRemix)"),
                new Music("Mark Knight& Ben Remember - LetMe Go"),
                new Music("Detlef - Jaydee"),
                new Music("Gorillaz - Busted&Blue (YottoRemix)"),
                new Music("Illius&Barrientos - California"),
                new Music("Cristophft. Forrest - The Sign"),
                new Music("Camelphat - Cola"),
                new Music("Eric Prydz - Pjanoo"),
                new Music("Icarus ft Talay Ridney - Trouble (Weiss Remix)"),
                new Music("Mutiny Uk & Rhythm Masters - Playing Out"),
                new Music("Armand Van Helden - i Need a Painkiller"),
                new Music("Format - Dance (Funkerman Remix)"),
                new Music("Cardi B - Bodak Yellow (CID Remix)"),
                new Music("Claude VonStroke - Barrump (Billy Kenny Remix)"),
                new Music("Antoine Delviq - Disciples"),
                new Music("CID - Creepin"),
                new Music("Marton Solveig ft. Alma - All Star (Mercer Remix)"),
                new Music("Billy Kenny - Trip Report"),
                new Music("Tomy Romera - Fire Inside"),
                new Music("Gorgon City - Primal Call"),
                new Music("Tommy Trash - Sinners (DRS Remix)"),
                new Music("MK- 17"),
                new Music("Gorgon City - Primal Call"),
                new Music("Motez - The Future (Purple Disco Machine Remix)"),
                new Music("Set Mo - I Belong Here (Kc Lights Remix)"),
                new Music("Olav Basoski ft. Stanford - My House"),
                new Music("Tony Tomera - Fire Inside"),
                new Music("Martin Solveig ft. Alma - All Star (Mercer Remix)"),
                new Music("Lane 8 - March Of the Forest"),
                new Music("Rationale - Loving Life (Franky Rizardo Remix)"),
                new Music("Rocco - Only Drums"),
                new Music("Dubfire - Ribcage (Dense & Pika Remix)"),
                new Music("The Magician & TCTS - Slow Motion"),
                new Music("Nore En Pure - Fever"),
                new Music("Illius & Barrientos - California"),
                new Music("Rationale - Loving Life (Franky Rizardo Remix)"),
                new Music("Marcus Schossow - Rumble"),
                new Music("Sebjak & Bedmar & Adrien Rux - Last Summer"),
                new Music("Martin Solveig ft Alma - All Stars (Mercer Remix)"),
                new Music("Chris Lake & Chris Lorenzo - Nothing Better"),
                new Music("Lane 8 - March Of The Forest Cat"),
                new Music("&Me - Avalon"),
                new Music("Juliet - Avalon (Jaques Lu Cont Versus Remix)"),
                new Music("Motez&Cleopatra - The Future"),
                new Music("Alex Adair .- Casual (Thomas Gold Remix)"),
                new Music("Chris Lake & Chris Lorenzo - NothingBetter"),
                new Music("Katrella - FindOurWay"),
                new Music("La Fuente - LIT"),
                new Music("Hiisak& Marco Carpentieri - GottaSay"),
                new Music("Go Freak - PutIt Down (KormakRemix)"),
                new Music("Mark Knight& Ben Remember - LetMe Go"),
                new Music("Detlef - Jaydee"),
                new Music("Gorillaz - Busted&Blue (YottoRemix)"),
                new Music("Illius&Barrientos - California"),
                new Music("Cristophft. Forrest - The Sign"),
                new Music("Camelphat - Cola"),
                new Music("Eric Prydz - Pjanoo"),
                new Music("Gershon Jackson - Huggin A Luvin (Chocolate Puma Remix)"),
                new Music("James Curd - PleaseDon't Play (CamelphatRemix)"),
                new Music("DepecheMode - GoingBackwards (ClaptoneRemix)"),
                new Music("Mark Knightft. RaggaTwins - MoveOn"),
                new Music("Marcus Schossow - Rumble"),
                new Music("Bakermatft. Kiesza - Don'tWantYou Back (Mat Joe Remix)"),
                new Music("Go Freek - PutIt Down"),
                new Music("Chris Lake - GiveHer Right Back"),
                new Music("Sinden - Bruk Out"),
                new Music("Ibranovski - NoseCandy"),
                new Music("Simon Kidzoo - Pop The Trunk (SJ & RM Remix)"),
                new Music("DaveWinnel - Kazoo"),
                new Music("SanderKleinenberg& Boris Smith - Trouble"),
                new Music("Jean Baccarezza - DoItLikeIt"),
                new Music("Mark Knight& Ben Remember - LetMe Go"),
                new Music("Maya Jane Coles - Go On And MakeItThrough"),
                new Music("Kc Lights feat Rae Hall - Sundown (Loving Me)"),
                new Music("Mark Knight & Ben Remember - Let Me Go"),
                new Music("Dave Winnel - Kazoo"),
                new Music("La Fuente - LIT"),
                new Music("Boeke - Favela"),
                new Music("Mark Knight ft. The Ragga Twins - Move On"),
                new Music("Basement Jaxx - Randez Vu (Jesse Garcia Edit)"),
                new Music("Biscits - Real Low (Billy Kenny Remix)"),
                new Music("Wolsch & Larry Mendes - All Day"),
                new Music("Ibranovski - Nose Candy"),
                new Music("Mercer - Quazar"),
                new Music("Dj S.K.T - Must Be The Music"),
                new Music("Mark Knight & Ben Remember - Let Me Go"),
                new Music("James Curd - Please Don't Play (Camelphat Remix)"),
                new Music("Gianni Bini & The Rituals - Shake Your Booty"),
                new Music("Mark Knight ft. Ragga Twins - Move On"),
                new Music("Jean Bacarreza & Andruss - Do It Like It"),
                new Music("Chris Lake - Give Her Right Back"),
                new Music("Ibranovski - Nose Candy"),
                new Music("Boeke - Favela"),
                new Music("Simon Kidzoo - Pop The Trunk (SJRM Remix)"),
                new Music("Jesee Rose & Avon Stringer - Pressure"),
                new Music("Gerahon Jackson - Huggin A Luvin (Chocolate Puma Remix)"),
                new Music("Muzzaik - Down So Long"),
                new Music("High Contrast - The Beat Don't Feel The Same"),
                new Music("Rudimental ft. James Arthur - Sun Comes Up (Offaiah Remix)"),
                new Music("DM - Going Backwards (Claptone Remix)"),
                new Music("Basement Jaxx - Randez Vu (Jesse Garcia Remix)"),
                new Music("Jesse Rose & Avon Stringer - Pressure"),
                new Music("Benin- Drop The Pressure (Skapes Remix)"),
                new Music("Damien N-Drix & STV - Let It Ring"),
                new Music("Felix Jaehn & Hight & Alex Aiono - Hot 2 Touch (Kyle Watson Mix)"),
                new Music("Camelphat - Trip"),
                new Music("Pryda - Himan Behavior"),
                new Music("Alex Adair - Casual (Felon Remix)"),
                new Music("The Kisser - Love Is The Answer"),
                new Music("Callim Beattie - Man Behind The Sun (Low Steppa Remix)"),
                new Music("Los Suruba & Dennis Cruz ft. Celeda - Funk You"),
                new Music("Dean Mason - Departures"),
                new Music("Camelphat - Cola"),
                new Music("Endor - Snake Charmer"),
                new Music("Miguel O Syrah Vs MAW - Arawak Work (Kryder Edit)"),
                new Music("Genairo Nvilla & Born Faya Loud Faya"),
                new Music("Martin Solveig - Places (Billy Kenny Remix)"),
                new Music("Ponctual - What I Love (Kc Lights Remix)"),
                new Music("Boston Bun - Missing You"),
                new Music("Mercer - Opium"),
                new Music("Madou - NowhereElse"),
                new Music("Sentre - LostIn The Moment"),
                new Music("The Blaze - Territory"),
                new Music("Cristophft. JemCooke - Feel"),
                new Music("Secondcity - Kwelanga"),
                new Music("Camelphat - Gypsy King"),
                new Music("Dj. S.K.T - Jack The Jack"),
                new Music("Prok&Fitch - Nodding Dog"),
                new Music("Biscits - Real Low (BillyKennyRemix)"),
                new Music("Eli Brown - Got The Power"),
                new Music("DukeDumont&Gorgon City - Real Life (SolardoRemix)"),
                new Music("Audion - MouthToMouth (Dense&PikaRemix)"),
                new Music("Boston Bun - MissingYou"),
                new Music("Madou - Nowhere Else"),
                new Music("Sentre - Lost In The Moment"),
                new Music("The Blaze - Territory"),
                new Music("Cristoph ft. Jem Cooke - Feel"),
                new Music("Secondcity - Kwelanga"),
                new Music("Camelphat - Gypsy King"),
                new Music("Dj. S.K.T - Jack The Jack"),
                new Music("Prok & Fitch - Nodding Dog"),
                new Music("Biscits - Real Low (Billy Kenny Remix)"),
                new Music("Eli Brown - Got The Power"),
                new Music("Duke Dumont & Gorgon City - Real Life (Solardo Remix)"),
                new Music("Audion - Mouth To Mouth (Dense &Pika Remix)"),
                new Music("Boston Bun - Missing You"),
                new Music("Alex Adair - Casual (Felon Remix)"),
                new Music("The Kisser - Love Is The Answer"),
                new Music("Callim Beattie - Man Behind The Sun (Low Steppa Remix)"),
                new Music("Los Suruba & Dennis Cruz ft. Celeda - Funk You"),
                new Music("Dean Mason - Departures"),
                new Music("Camelphat - Cola"),
                new Music("Endor - Snake Charmer"),
                new Music("Miguel O Syrah Vs MAW - Arawak Work (Kryder Edit)"),
                new Music("Genairo Nvilla & Born Faya Loud Faya"),
                new Music("Martin Solveig - Places (Billy Kenny Remix)"),
                new Music("Ponctual - What I Love (Kc Lights Remix)"),
                new Music("Boston Bun - Missing You"),
                new Music("Mercer - Opium"),
                new Music("Madou - NowhereElse"),
                new Music("Sentre - LostIn The Moment"),
                new Music("The Blaze - Territory"),
                new Music("Cristophft. JemCooke - Feel"),
                new Music("Secondcity - Kwelanga"),
                new Music("Camelphat - Gypsy King"),
                new Music("Dj. S.K.T - Jack The Jack"),
                new Music("Prok&Fitch - Nodding Dog"),
                new Music("Biscits - Real Low (BillyKennyRemix)"),
                new Music("Eli Brown - Got The Power"),
                new Music("DukeDumont&Gorgon City - Real Life (SolardoRemix)"),
                new Music("Audion - MouthToMouth (Dense&PikaRemix)"),
                new Music("Boston Bun - MissingYou"),
                new Music("Tchami - World To Me"),
                new Music("Fatboy Slim - Where U Iz (Eats Everything Remix)"),
                new Music("Shan Gers Janson - Surrender"),
                new Music("Punctual - What I Love (Kc Lights Remix)"),
                new Music("Yotto - Wilderness Girl"),
                new Music("Alexis Rapharl - It's Kinda Jazzy"),
                new Music("Franky Rizardo - Feel Alright"),
                new Music("Duke Dumont & Gorgon City - Real Life (Solardo Remix)"),
                new Music("Camelphat - NYP2"),
                new Music("Yousef - Life Is Too Short"),
                new Music("Aevion - Summer"),
                new Music("Boston Bun - Missing You"),
                new Music("Madou - Nowhere Else"),
                new Music("Sentre - Lost In The Moment"),
                new Music("The Blaze - Territory"),
                new Music("Cristoph ft. Jem Cooke - Feel"),
                new Music("Secondcity - Kwelanga"),
                new Music("Camelphat - Gypsy King"),
                new Music("Dj. S.K.T - Jack The Jack"),
                new Music("Prok & Fitch - Nodding Dog"),
                new Music("Biscits - Real Low (Billy Kenny Remix)"),
                new Music("Eli Brown - Got The Power"),
                new Music("Duke Dumont & Gorgon City - Real Life (Solardo Remix)"),
                new Music("Audion - Mouth To Mouth (Dense &Pika Remix)"),
                new Music("Boston Bun - Missing You"),
                new Music("Boston Bun - Missing You"),
                new Music("Ferreck Dawn & Robosonic - Old Dollar"),
                new Music("Rudimental, James Arthur - Sun Comes Up (Offaiah Remxi)"),
                new Music("Jiggler - Impact"),
                new Music("Dj S.K.T - Jack That Jack"),
                new Music("Mercer - Juicy"),
                new Music("Biscits - Real Low (Billy Kenny Remix)"),
                new Music("Muzzaik & Stadiumx - Aria"),
                new Music("Nari & Milani - I Am Alright"),
                new Music("Aevion - Summer"),
                new Music("Tchami - Adieu"),
                new Music("Yotto - Wilderness Girl"),
                new Music("Duke Dumont & Gorgon City - Real Life (Solardo Rmx)"),
                new Music("Cassius - ibifornia (Myd Remix)"),
                new Music("Oliver Heldens - Ibiza 77"),
                new Music("Can U Feel it (Rootkit Remix)"),
                new Music("Watermat & Pep & Rush - Ruff Like This"),
                new Music("Martin Solveig - Places (Billy Kenny Remix)"),
                new Music("Toak - Feeling Me"),
                new Music("Bodyrox - Yeah Yeah (Chocolate Puma Remix)"),
                new Music("Dj Khaled ft Beyonce ft Jayz - Shining (CID Remix)"),
                new Music("Raye - The Line (Offaiah Remix)"),
                new Music("Aevion - Summer"),
                new Music("Boston Bun - Missing You"),
                new Music("J-Trick &Tom Budin - Heard Right"),
                new Music("Unknow"),
                new Music("Louder - The Move"),
                new Music("Sanjin Mantra Edit"),
                new Music("Jamis MAD M.A.C - Renegade Master (Dimitry Vegas &Like Mike Remix)"),
                new Music("Unknown"),
                new Music("Chocolate Puma - Weekendscrab"),
                new Music("Mercer - Qazar"),
                new Music("Baha - Awakening (Michael Brun Mix)"),
                new Music("Shiba san - Okay (Dave Winnel Remix)"),
                new Music("Bodyrox - yeah Yeah (Chocolate Puma Remix)"),
                new Music("Tiesto &KSHMR ft. Vassy - Secrets (Don Diablo's VIP Mix)"),
                new Music("Muzzaik & Stadiumx - Dj Saved My Life"),
                new Music("Bart B More & Chocolate Puma - Rising Up"),
                new Music("The Magician ft. Brayton Bowman - Shy (CID Remix)"),
                new Music("Kryder & Leandro De Silva - Uh Oh"),
                new Music("Prok & Fitch ft Florence - Say My Noise"),
                new Music("Miguel O Sirah & MAW - Arawak Work (Kryder Edit)"),
                new Music("Eli Brown - Got The Power"),
                new Music("Tube & Berger - Set It Off (Kryder Remix)"),
                new Music("Gorillaz - Ascension (Nic Fanciulli Remix)"),
                new Music("Dj Licious - I Hear You Calling (Kc Lights Remix)"),
                new Music("Dillon Francis - Say Less ft. G-Eazy - (Gorgon City Remix)"),
                new Music("Raye - The Kive (Offaiah Rmx)"),
                new Music("Camelphat - Gypsy King"),
                new Music("Olin Bastita -Funkin"),
                new Music("Kryder & Leandro Da Silva - Uh Oh"),
                new Music("Mark Knight & Rene Amesz - Live Stream"),
                new Music("F-Man - Inner"),
                new Music("Gorillaz - Ascension (Nic Fanciulli Rmx)"),
                new Music("Bodyrox - Yeah Yeah (Chocolate Puma Rmx)"),
                new Music("Nari & Milani - Twilight"),
                new Music("Yotto -Wilderness Girl")
            };
        }
    }
}
