using PoLaKoSz.MusicFM.Models;
using System.Collections.Generic;

namespace PoLaKoSz.MusicFM.Tests.Integration.StaticResources.MusicKillers
{
    public static class DeepLison
    {
        public static readonly List<Music> Tracklist;



        static DeepLison()
        {
            Tracklist = new List<Music>()
            {
                new Music("DirtyFreek, Reload - Something I CanDo (Original Mix)"),
                new Music("Anto - NobodyElse"),
                new Music("Skyni - FeelThat"),
                new Music("Tom Bull ft. Asha - On The Dancefloor"),
                new Music("Kanye West &LilPump - I Love It (Amice Remix)"),
                new Music("Paul Sirrell - Hold You Back"),
                new Music("Karim B - Tell Me"),
                new Music("Henri - AloneWithYou (Original Mix)"),
                new Music("Zhu - Faded (FR!ZZYRemix)"),
                new Music("Paul Sirrell&KymberleyMyles - WhatYouDo"),
                new Music("Solu Music feat. Kimblee - Fade (Paul SirrellRemix)"),
                new Music("CheatCodes, Little Mix - OnlyYou (ConnorMRemix)"),
                new Music("TKDJS - Don'tLeave"),
                new Music("Chris Watson - NeverGonna Be (LTGTR Remix)"),
                new Music("Bonnie McKee - MadMad World (MT SOUL Remix)"),
                new Music("Fabienne - Sunstroke (EndorRemix)"),
                new Music("Poolhaus - Percolatin"),
                new Music("KaiKahana - Your Love (ft. CecLopez)"),
                new Music("Alice Deejay - BetterOffAlone (Josh Hunter Bootleg)"),
                new Music("NeverAlone (TwoModestRemix)"),
                new Music("Pyne - LetMe Down"),
                new Music("Sigala& Ella Eyre - Came Here for Love (NLK Remix)"),
                new Music("Varcity - Joy In Me Robbie"),
                new Music("Secondcityft. Ali Love - WhatCan I Do (LS2 Remix"),
                new Music("MACY - Night is close in (Original Mix)"),
                new Music("Truth x Lies - GiveItToMe"),
                new Music("Route 94 - My Love (ORBZ Remix)"),
                new Music("ShakeSofa - MovetoMe (Original Mix)"),
                new Music("PINEO & LOEB - Circlesft. Kayo (Chase KannelRemix)"),
                new Music("Groovefore&Stevens - Streets"),
                new Music("BurakYeter&DanelleSandoval - Tuesday (Harmo&VibesRemix)"),
                new Music("Empire Of The Sun - WeAre The People (SilhouetteRemix)"),
                new Music("AYER - MyHands (Truth x LiesRemix)"),
                new Music("Adina Howard - Freak Like Me (TRP Remix)"),
                new Music("LS2 - Teardrops"),
                new Music("Pyne - Your Love"),
                new Music("Whitney Houston - It'sNotRight (Damian Gray Remix)"),
                new Music("BenDelay - It'sOnYou"),
                new Music("Tube Berger Juliet Sikora - ComeOnNow (SetItOff)"),
                new Music("Luniz - I Got 5 OnIt (Samuel K Remix)"),
                new Music("Silhouette - PleaseDon´t"),
                new Music("T - Pain - Up Down (DoThisAll Day) ft. B.o.B (CharlieMorrowRemix)"),
                new Music("Madison Mars feat. Caslin - AllTheyWanna Be (RetroVisionRemix)"),
                new Music("Tchami - Adieu (ChaceRemix)"),
                new Music("DistantNatured& Giorgio Sainz - Good ToMe (Extended Mix)"),
                new Music("Kiesza - Hideaway (LS2 Remix)"),
                new Music("Major Lazer x DJ Snake (feat.MØ) - LeanOn (LS2 Remix)"),
                new Music("DeneAntony - TakeMeHigher (Original Mix)"),
                new Music("Paul Sirrell - SayYou Love Me (Original Mix)"),
                new Music("BasementJaxx - Unicorn (LS2 Remix)"),
                new Music("Futose - Deeper Love"),
                new Music("Hot Since 82 - Buggin' (feat. JemCooke)"),
                new Music("Charlie Black - WantMe (Anto&RareCandyRemix)"),
                new Music("Klosman - All In (feat. Vita Schmidt)"),
                new Music("CallumMcBride - Almost Home (Alex HobsonRemix)"),
                new Music("DFUX - My Love (FT. Vili)"),
                new Music("Major Lazerfeat. Justin Bieber& MØ - ColdWater (LS2 Remix)"),
                new Music("Signum - WhatYa Got ForMe (Decor& Dean KielyRemix)"),
                new Music("Paul Sirrell - Hesitate (Original Mix)"),
                new Music("Clean Bandit - Rather Be (LS2 Remix)"),
                new Music("Paul Sirrell - WhatYoure Feeling"),
                new Music("Paul Sirrell - WhatWouldWeDo"),
                new Music("Dallerium, CEA &Ferington - You& I"),
                new Music("DukeDumontfeat. AME - Need U (100%) (CharlieMorrowRemix)"),
                new Music("Galantis - Runaway (U & I) (LS2 Remix)"),
                new Music("Secondcity - I WannaFeel (Samuel K Bootleg)"),
                new Music("MischaDaniels& Dennis Christopher feat. Daisy - Feelin U"),
                new Music("John Gibbons - Would I Lie ToYou (Kyle MeehanRemix)"),
                new Music("LS2 feat. Lana x - TouchMe 9. Silhouette - Love Me"),
                new Music("SwingKings - BurningUp (Paul SirrellElectroSpeedGarage Mix)"),
                new Music("DestinysChild - SayMyName (SilhouetteRemix)"),
                new Music("Namára - My Love"),
                new Music("Oliver Heldens X Becky Hill - Gecko (PearseDunneRemix)"),
                new Music("ColourCastle& VØ - ComeWithMe (Original Mix)"),
                new Music("Gala - FreedFromDesire (DubRoccaRemix)"),
                new Music("Paul Sirrell - WhatWouldWeDo"),
                new Music("Dallerium, CEA &Ferington - You& I"),
                new Music("DukeDumontfeat. AME - Need U (100%) (CharlieMorrowRemix)"),
                new Music("Galantis - Runaway (U & I) (LS2 Remix)"),
                new Music("Secondcity - I WannaFeel (Samuel K Bootleg)"),
                new Music("MischaDaniels& Dennis Christopher feat. Daisy - Feelin U"),
                new Music("John Gibbons - Would I Lie ToYou (Kyle MeehanRemix)"),
                new Music("LS2 feat. Lana x - TouchMe 9. Silhouette - Love Me"),
                new Music("SwingKings - BurningUp (Paul SirrellElectroSpeedGarage Mix)"),
                new Music("DestinysChild - SayMyName (SilhouetteRemix)"),
                new Music("Namára - My Love"),
                new Music("Oliver Heldens X Becky Hill - Gecko (PearseDunneRemix)"),
                new Music("ColourCastle& VØ - ComeWithMe (Original Mix)"),
                new Music("Gala - FreedFromDesire (DubRoccaRemix)"),
                new Music("Aaliyah - IfYourGirlOnlyKnew (Boehm 2018 Brazilian Summer Remix)"),
                new Music("Beave& LTGTR - Viper"),
                new Music("BlocBoy JB & Drake - LookAlive (REESE Remix)"),
                new Music("Marcus Schössow - White Lies"),
                new Music("OFFAIAH - Private Show (Carl Flanagan&Ben Kaye Remix)"),
                new Music("Aaliyah - AreYouThatSomebody (DellmonRemix)"),
                new Music("J Balvin, Willy William - Mi Gente (DJ TimstarPrivateRemix)"),
                new Music("Sam Smith - Pray (MK Remix)"),
                new Music("Robert Cristian - Desire (Original Mix)"),
                new Music("Sam Bassline - AloneWithYou"),
                new Music("Bissett - WheneverI'm Down"),
                new Music("Fabich - One, Two (Original Mix)"),
                new Music("Ferdinand Weber &Fabich - Aaliyah"),
                new Music("Joe Stone - The Partyft. Montell Jordan"),
                new Music("Silhouette - I'mNotPretending"),
                new Music("Block&Crown - FeelMy Love"),
                new Music("PAX - ElectricFeel [Glasgow Underground]"),
                new Music("Alaia&Gallo - SoSpecial (Original Mix)"),
                new Music("Anjali World- Uh Oh (Ryan NicholsRemix)"),
                new Music("Carl Flanagan - CoverItUp (Original Mix)"),
                new Music("DirtyFreek - All I Need (Mason Remix)"),
                new Music("GianniBini& The Rituals - Sun Goes down"),
                new Music("PAX - ElectricFeel (Extended Mix)"),
                new Music("Schiller - I FeelYou (NikkoCultureRemix)"),
                new Music("M-22 ft. Medina - First Time (SammyPorterRemix)"),
                new Music("Alex Monaco - Cabrio (Dapa Deep Remix)"),
                new Music("Mike Posner - I Took A Pill In Ibiza (DJ Raja & Jamie M Remix)"),
                new Music("Hayden James - JustFriends (ft. Boy Matthews)"),
                new Music("Mark Maxwell - Don'tChange (The Channel)"),
                new Music("Amy Winehouse - Rehab (Pantheon Remix)"),
                new Music("Dan Judge& Jordan King X Jennifer Hudson - It'sYour World"),
                new Music("Soulsearcher 'Can’tGetEnough!' (Angelo FerreriExtendedSweety Mix)"),
                new Music("The Distance&Riddick - WhereDid U Go (Original Mix)"),
                new Music("Wamdue Project - King Of MyCastle (Craig KnightRemix)"),
                new Music("Weiss - FeelMyNeeds (Original Mix)"),
                new Music("Kwabs - FightFor Love (BlondeRemix)"),
                new Music("Silhouette - You'llNeverSeeMe"),
                new Music("Anto&Lyle M - AllOnMy Mind"),
                new Music("C-Bool - Wonderland (Giorgio Sainz&DistantNaturedRemix)"),
                new Music("Calvin Buckley&LukeP - Electric"),
                new Music("Futosé - NeverAround"),
                new Music("M 22 ft. Medina - First Time (Endor Radio Edit)"),
                new Music("Shakedown 'AtNight' (PurpleDiscoMachineRemix)"),
                new Music("UltrxNxte - Free (Craig KnightRemix)"),
                new Music("DemiLovato - SorryNotSorry (The HuxRemix)"),
                new Music("Destiny'sChild - SayMyName (SHARKEY x BeaveRemix)"),
                new Music("Francois & Louis Benton - Got No Love"),
                new Music("Nalestar - Out Of Love"),
                new Music("Sean Paul feat. BlueCantrell - Breathe (Calvin BuckleyRemix)"),
                new Music("CamelPhatft. A*M*E - Paradigm (Tom Hall Remix)"),
                new Music("DuaLipa - Be The One (BeaveRemix)"),
                new Music("Thomas Anthony feat. White Gypsy - Tom's Diner (Club Mix)"),
                new Music("WhatSoNotft. WinonaOak - Beautiful (VolacRemix)"),
                new Music("NobleTonezfeat Chris Perham - DancebytheWater"),
                new Music("Brandy & Monica - The Boy Is Mine (Jake Faust Remix)"),
                new Music("Guz&Tough Love - Dancin' KindaClose"),
                new Music("Will Fast - The Lead Love (Original Mix)"),
                new Music("Celeda - Music Is The Answer (VolkanUca&HuseyinOnen 2K18 Remix)"),
                new Music("Jerome Price - GetMeThere (ft. Alex Mills)"),
                new Music("NDUA - This Love feat. Lyrique (ANTO Remix)"),
                new Music("Rihanna - Work (Beave x Martin & Rami Remix)"),
                new Music("Calvin Harris, DuaLipa - One Kiss (Oliver HeldensRemix)"),
                new Music("Jax Jones ft. InaWroldsen - Breathe (Richard TraceyRemix)"),
                new Music("Leona Lewis - Bleeding Love (BeaveRemix)"),
                new Music("ManuChao - Bongo Bong (Divolly&Markward Bootleg)"),
                new Music("Sebastian Knight - You (Original Mix)"),
                new Music("BingoPlayersvs. Chocolate Puma - DiscoElectrique (Vocal Mix)"),
                new Music("BenassiBrosfeat. Dhany - Hit MyHeart (NikkoCultureRemix)"),
                new Music("Martin Badder ‘SeeItThroughMyEyes’ (Extended Mix)"),
                new Music("SonnyFoderafeat. Alex Mills - TakeMe Down"),
                new Music("Zinc - Show Me (Cause&AffectRemix)"),
                new Music("DateNightft. The CoconutKids - LayIt Down (Modern CitizensRemix)"),
                new Music("Alma - Good Vibes (TRU ConceptRemix)"),
                new Music("BLVK JVCK - MineLuv (DalleriumRemix)"),
                new Music("Shakedown - AtNight (LeventOzbayRemix)"),
                new Music("Brandy - I Could Be Wrong (2018 UK Edit)"),
                new Music("Jennifer Lopez - WaitingForTonight (Karl Mac Remix)"),
                new Music("Junior Jack - My Feeling (Richard TraceyRemix)"),
                new Music("Chicanefeat. MoyaBrennan - Saltwater (JodyWisternoffRemix)"),
                new Music("Anton Powers&PixieLott - Baby (RobbieGRemix)"),
                new Music("James Hypeft. Kelli-Leigh - More Than Friends (Alex HobsonRemix)"),
                new Music("Madonna - Frozen (A-MaseNudiscoRemix)"),
                new Music("The Magicianfeat. BraytonBowman - SHY (CID Remix)"),
                new Music("ColdLies - Best Friend"),
                new Music("Marvin Gaye - SexualHealing (TRP Deep House Club Mix)"),
                new Music("NO WAY BACK - It'sNotRight, ButIt'sOkay"),
                new Music("GAB - OneNight"),
                new Music("Inpetto - Needin' U So"),
                new Music("RareCandy& Rich James - HappenedToMe"),
                new Music("Axwell&Ingrosso – More Than YouKnow (ReznikovRemix)"),
                new Music("Sam Divine& Curtis Gabriel featuringNatConway 'Confessions' (Waiting Mix)"),
                new Music("Max Nikitin - WTF"),
                new Music("N Trance - SetYou Free (Craig KnightRemix)"),
                new Music("Studioheist - AllMy Love"),
                new Music("Ciara - Overdose (Thando1988 Remix)"),
                new Music("Husky &Arcade 82 - Game Tight"),
                new Music("Delta Jack - SayWhatYou Like"),
                new Music("Lloyd - GetItShawty (DrywallJungleRemix)"),
                new Music("Danny Tedaglia - Music Is The Answer (BeaveRemix)"),
                new Music("FerreckDawn&Robosonic - In Arms"),
                new Music("Husky feat. Shyam P - Lost Without U"),
                new Music("DukeDumont - Need U feat. AME (MotiveRemix)"),
                new Music("ZaraLarsson - I Would Like (Miscris, Kaan Pars Remake)"),
                new Music("Triplex&Camvift. CorinnaDennig - FaceMe (Aaron NorthRemix)"),
                new Music("Russell Small& DNO P - Love OnMy Mind (feat. Amanda Wilson)"),
                new Music("Maya Jane Coles - WhatTheySay (Original Mix)"),
                new Music("Chris Lorenzo - SleepTalkft. Alex Mills (Calvin BuckleyRemix)"),
                new Music("MoeTurk - JustLike I Love You (Original Mix)"),
                new Music("Marvin Gaye - HeardItOn The Grapevine (Alex PrestonRework)"),
                new Music("DJ Danila ft. Gosha - Don't GiveUp (KeepOnShining)"),
                new Music("Baytek - Got The Love (Pantheon and ColourCastleRemix)"),
                new Music("Max Oazoft. CAMI - WhatIs Love (The Distance&IgiRemix)"),
                new Music("Brandy &Monica - The Boy IsMine (LupexxRemix)"),
                new Music("MNEK x Disclosure - White Noise (XYconstantRemix)"),
                new Music("Chase& Status - Time (Ft. Delilah) (Adam WongRemix)"),
                new Music("Adam Wong - Let's Go"),
                new Music("Leandro Da Silva & Jude Frank - Freed From Desire (Remix)"),
                new Music("Laika & Strelka, DirrtyDishes - Jacky and Jane"),
                new Music("Luca Debonaire Kiki Doll - Ridiculousness"),
                new Music("Styline - Ignition"),
                new Music("Afrojack, Dimitri Vegas & Like Mike & NERVO - The Way We See The World (Levito Remix)"),
                new Music("Brohug x Malaa - Bylina Paparazzi (Antoine Delvig Mashup)"),
                new Music("Snap - I've Got The Power (Cazztek Remix)"),
                new Music("Daft Punk - Harder Better Faster Stronger (Just Nik Remix)"),
                new Music("Aaliyah - Are You That Somebody (Jungle Jim Bootleg)"),
                new Music("Kid Cudi - Day & Night (Scott Forshaw & Greg Stainer Remix)"),
                new Music("Bisbetic & Pink Is Punk - Push The Feeling On"),
                new Music("Bob Marley - Is This Love (Ben Rainey Remix)"),
                new Music("B Young - Jumanji (Shift K3Y Remix)"),
                new Music("Lika Morgan - Sweet Dreams (Andrey Keyton & Sharapov Remix)"),
                new Music("Perfecto Allstarz x Freejak - Reach Up"),
                new Music("Avicii feat. Andreas Moe - Last Dance (Vocal Club Mix)"),
                new Music("Avicii vs. Lenny Kravitz - Superlove"),
                new Music("+ Speech of Avicii in Track #2 included (Award Winning)"),
                new Music("Avicii - Pure Grinding (Elie Rizko Remix)"),
                new Music("Avicii - Hey Brother (TEEMID & Tessa Rose Jackson Cover)"),
                new Music("Avicii - Waiting For Love (Fabich Remix)"),
                new Music("Tim Berg - Seek Bromance (Jerome Price Remix)"),
                new Music("Avicii - Wake Me Up (Elektrofil Edit)"),
                new Music("+ Speech of Avicii in Track #7 included (Interview)"),
                new Music("Avicii vs. Nicky Romero - I Could Be The One (Pearse Dunne Remix)"),
                new Music("Avicii - Levels (VAVO Remix)"),
                new Music("Avicii - Waiting For Love (Addal Remix)"),
                new Music("Avicii - You Make Me (Throttle Remix)"),
                new Music("Avicii - Addicted To You (Florian Paetzold Bootleg)"),
                new Music("Avicii ft. Rita Ora - Lonely Together (Danny Dove Remix)"),
                new Music("Rescue& Steve Synfull - Dont Let Go"),
                new Music("Sandy Rivera - TryA Little Tenderness"),
                new Music("Milk&Sugar - Let The Sun Shine (Milk&SugarRemix)"),
                new Music("Me&MyToothbrush - Sexy Lady"),
                new Music("Block&Crown - MoveMy Body"),
                new Music("Yuga& Mr. Saccardo - No More Dream"),
                new Music("Sandy Rivera - I Can't Stop (Dario D'AttisRemix)"),
                new Music("Dario D'Attis - SunshinePeople"),
                new Music("Nora En Pure - Fever (Original Club Mix)"),
                new Music("Block&Crown - JustCan't GetEnough (Original Club Mix)"),
                new Music("MK - 17 (eSquire House Remix)"),
                new Music("Aaliyah - IfYourGirlOnlyKnew (Boehm 2018 BrazilianSummerRemix)"),
                new Music("Avicii& Sebastian Drums - MyFeelingsForYou (SpaveechRemix)"),
                new Music("AlwaysGonna Be feat. Alex Mills (LowSteppaRemix)"),
                new Music("KylieMinogue - Slow (SllashRemix)"),
                new Music("HGZ - Wanna Be (Pascal LetoublonRemix)"),
                new Music("TWO LANES - Long Way Home (JetiqueRemix) [ft. HYM]"),
                new Music("Shannon - Let The Music Play (James BluckRemix)"),
                new Music("Lika Morgan - Holding On"),
                new Music("Skyni - Be Together"),
                new Music("Stardust - Music SoundsBetterWithYou (Eat More CakeRemix)"),
                new Music("Ariana Grande - TouchIt (CharlieMorrowRemix)"),
                new Music("WHTKD - WHTNSE"),
                new Music("OneRepublic - If I LoseMySelf (Bentley Grey Remix)"),
                new Music("Kygo&SelenaGomez - ItAin't Me (Alex HobsonRemix)"),
                new Music("Gala - FreedfromDesire (SteEssenceRework)"),
                new Music("Kid Massive - TouchMefeat. Elliotte Williams N'Dure (Carl TricksRemix)"),
                new Music("Block&Crown - Apple Knocker (Original Mix)"),
                new Music("FatboySlim - Star 69 (LO99 Remix)"),
                new Music("Justin Timberlake – Can´t Stop The Feeling (TannergaardRemix)"),
                new Music("Punctual - What I Love (KC LightsRemix)"),
                new Music("Simioli - The Horn Song (Marco SantoroRemix)"),
                new Music("Agent Greg &NimoIero - Let The Music (The CubeGuys Mix)"),
                new Music("Jude& Frank: FrenchFries (Original Mix)"),
                new Music("Leandro Da Silva - I Love House Music (Club Mix)"),
                new Music("Block&Crown - FeelMy Love"),
                new Music("JAG – Miyabi"),
                new Music("Nicola Fasano, Yuga& Mr. Saccardo - SavedMy Life (Original Mix)"),
                new Music("SonnyFodera& MANT - MovingUp (Original Mix)"),
                new Music("Sunnery James & Ryan Marcianovs Thomas Newson - I'll House You (Extended Mix)"),
                new Music("ThreeDrives - Greece 2000 (BahlzackCreations 2017)"),
                new Music("Luca Debonaire& Chris Marina - WatcingMe (Original Mix)"),
                new Music("Still Young - White Label (Is This Love)"),
                new Music("ElektrikDisko - Everybodys Free (M1 Remix)"),
                new Music("ChildishGambino - Heartbeat (KamikarzySolowRemix)"),
                new Music("Earth, Wind&Fire - September (Jack King Remix)"),
                new Music("David Guetta - World IsMine (No Hopes ABCDEEP Remix)"),
                new Music("Anton Ishutinfeat. Note U – Be MyLover (SharapovRadio Mix)"),
                new Music("Black Caviar - TouchIt"),
                new Music("DannyTenaglia - Music Is The Answer (Ron VeinRemix)"),
                new Music("Modjo - Lady (Extended Mix)"),
                new Music("Ben Delay - I Never Felt So Right (Club Mix)"),
                new Music("Bissett - OnMy Mind (Pt1 Organ)"),
                new Music("Mark Knight - Alright (Original Club Mix)"),
                new Music("Ashanti - Happy (LupexxRemix)"),
                new Music("DeneAntony - TakeMeHigher (Original Mix)"),
                new Music("Deep Criminal - No MatterWhere"),
                new Music("Corona - The Rhythm Of The Night (Sunlight Project Remix)"),
                new Music("Wankelmut& Emma Louise - My Head Is A Jungle (MK Remix)"),
                new Music("DubRocca - No OneButYou"),
                new Music("Beave - FeelSo Good"),
                new Music("Rihanna - WhereHaveYouBeen (Tom Hall Remix)"),
                new Music("BustaRhymes - TouchIt (BanzoliRemix)"),
                new Music("LS2 Feat. Lana - TouchMe"),
                new Music("Klosman - AllIn (feat. Vita Schmidt)"),
                new Music("Luurk - One Minute ft. Andre (USB PLAYERS Remix)"),
                new Music("Kings of Tomorrow - Finally (RobbieGRemix)"),
                new Music("Stromae - AlorsOnDanse (DubdogzRemix)"),
                new Music("Dwin - LaLaLaLaLa (GaullinRemix)"),
                new Music("Adam Lambert - GhostTown (USB PLAYERS Bootleg)"),
                new Music("Stardust - Music SoundsBetterWithYou (Tough Art & Hot BulletRemix)"),
                new Music("Gorgon City - Imagination (Weiss Remix) ft. Katy Menditta"),
                new Music("WHTKD - Say To Me (Lewis Teale Remix)"),
                new Music("Ferreck Dawn Redondo - Love Too Deep (Abstract Logic Remix)"),
                new Music("MK Ft. Alana - Always (Route 94 Remix)"),
                new Music("Justin Martin - Dont Go (Dusky"),
                new Music("Phil - You Needa Freak"),
                new Music("N69 - Take You There"),
                new Music("Andre Crom - New Day (Original Mix)"),
                new Music("Mark Knight – Your Love"),
                new Music("Secondcity - I Wanna Feel (DubRocca Remix)"),
                new Music("Booka Shade - Love Inc (Hot Since 82 Remix)"),
                new Music("Gorgon City feat. Vaults – All Four Walls (Deep House Cover)"),
                new Music("Monsta Boy – Sorry (DubRocca Remix)"),
                new Music("2Groove & Disord3r - Ready Or Not"),
                new Music("GAB - Summer Nights"),
                new Music("Love Decade - So Real (AwoL Remix)"),
                new Music("Sam Bassline - Missing You"),
                new Music("Aaron North - The Trip (Ride On A Meteorite)"),
                new Music("Lost Focus - Get U"),
                new Music("Rozalla - Everybodys Free (ConnorM Remix)"),
                new Music("DJ Ashes - If You Want It"),
                new Music("Secondcity - I Wanna Feel (Robin Tayger Remix)"),
                new Music("Night Crawlers - Push The Feeling On (LukeG 2017 Remix)"),
                new Music("Ryan Redmond - Do You Want Me Baby (Bissett Remix)"),
                new Music("Ryan Redmond - Heard It All Before"),
                new Music("VANDL - Wonder"),
                new Music("J. Latham - You Me"),
                new Music("James Oliver – Understand"),
                new Music("Adam Wong - Around U"),
                new Music("Tom Wigley Project 14 - Nightwatch"),
                new Music("DuaLipa - New Rules (Arizen Remix)"),
                new Music("Anto - The Music"),
                new Music("CreativeAdes - Deeper Love (Original Mix)"),
                new Music("CamilaCabello - Havana (Arizen Remix)"),
                new Music("Bissett - IntoMyRoom"),
                new Music("Luis Leon - BorrowedPlaces (Original Mix)"),
                new Music("Rui Da Silva - TouchMe (DubRoccaRemix)"),
                new Music("Finally – (Rick LiveRemix)"),
                new Music("Robin S - Show Me Love (Rick LiveRemix)"),
                new Music("Stevensft. ShereeHicks - YouWantIt (Giorgio SainzRemix)"),
                new Music("RaeSremmurd - Black Beatles (KjuusRemix)"),
                new Music("TorrenFoot - LøveMe (Tom Budin Remix)"),
                new Music("Catch (Groovefore& Giorgio SainzRemix)"),
                new Music("DubRocca - You Got MeBurning"),
            };
        }
    }
}
