using PoLaKoSz.MusicFM.Models;
using System.Collections.Generic;

namespace PoLaKoSz.MusicFM.Tests.Integration.StaticResources.MusicKillers
{
    public static class Yamina
    {
        public static readonly List<Music> Tracklist;



        static Yamina()
        {
            Tracklist = new List<Music>()
            {
                new Music("Dom Dolla – Take It"),
                new Music("Fisher – Stop It (Original Mix)"),
                new Music("JoerJunior – La Verité (Extended Version)"),
                new Music("Haechi & KYANU – Blockin"),
                new Music("BIJOU – Gotta Shine"),
                new Music("DJ Snake x Mercer – Let’s Get Ill"),
                new Music("Rob & Jack – Bashment Thing (Extended Mix)"),
                new Music("Zonderling, Don Diablo – Tunnel Vision"),
                new Music("Damien N-Drix – Ghetto Funk (Original Mix)"),
                new Music("Willy William – La La La(Extended Version)"),
                new Music("Will K vs. Fly Project – Café Leche vs. Toca Toca"),
                new Music("Reality Test feat. Shanti People – Passion (Original Mix)"),
                new Music("Chocolate Puma & Tommie Sunshine feat. MX2 – Tear This Mother Dow"),
                new Music("Tiesto & Dzeko ft. Preme & Post Malone – Jackie Chan"),
                new Music("Willy William – La La La"),
                new Music("Bounce Inc – Dump"),
                new Music("Joer Junior – La Verité"),
                new Music("Charlie Puth – Attention (Willcox Remix)"),
                new Music("Desiigner – Panda (Kubski Remix)"),
                new Music("Will K – Sour Milk"),
                new Music("Dan Deal – Trump This"),
                new Music("Selecta – G"),
                new Music("Tiesto & Ummet Ozcan – What You’re Waiting For"),
                new Music("Tommie Sunshine – Scrub The Ground"),
                new Music("Twoloud x Dj Kuba – Mirror on the wall"),
                new Music("J Balvin & Willy William – Mi Gente (Digital Junkiez Remix)"),
                new Music("Tujamo – One on One"),
                new Music("Follow The Flow – Nem tudja senki"),
                new Music("Status Quo – In The Army Now"),
                new Music("Dom Dolla – Take It"),
                new Music("Bram Fidder – Thirsty"),
                new Music("Malaa – Belleville"),
                new Music("Stupid Goldfish & Dashnation - Sneakers"),
                new Music("Willy William – La La La"),
                new Music("Tiesto & Dzekao ft. Preme & Post Malone – Jackie Chan"),
                new Music("Joer Junior – La Verité"),
                new Music("Twoloud – Mirror On The Wall"),
                new Music("Matisse – Take Off"),
                new Music("Martin Garrix & Khalid – Ocean (Don Diablo Remix)"),
                new Music("Kid Cudi – Day N Nite (Moksi Remix)"),
                new Music("Damien N Drinx – Scratch"),
                new Music("Chocolate Puma – Tear This Mother Down"),
                new Music("Big Shaq x Jauz – The Volume"),
                new Music("Mike Cervello – SMACK! (Moksi Remix)"),
                new Music("Dj Snake – Lets Get Ill"),
                new Music("Status Quo – In The Army Now"),
                new Music("Dom Dolla – Take It"),
                new Music("Fisher – Stop It (Original Mix)"),
                new Music("JoerJunior – La Verité (Extended Version)"),
                new Music("Haechi & KYANU – Blockin"),
                new Music("BIJOU – Gotta Shine"),
                new Music("DJ Snake x Mercer – Let’s Get Ill"),
                new Music("Rob & Jack – Bashment Thing (Extended Mix)"),
                new Music("Zonderling, Don Diablo – Tunnel Vision"),
                new Music("Damien N-Drix – Ghetto Funk (Original Mix)"),
                new Music("Willy William – La La La(Extended Version)"),
                new Music("Will K vs. Fly Project – Café Leche vs. Toca Toca"),
                new Music("Reality Test feat. Shanti People – Passion (Original Mix)"),
                new Music("Chocolate Puma & Tommie Sunshine feat. MX2 – Tear This Mother Dow"),
                new Music("Tiesto & Dzeko ft. Preme & Post Malone – Jackie Chan"),
                new Music("Willy William – La La La"),
                new Music("Bounce Inc – Dump"),
                new Music("Joer Junior – La Verité"),
                new Music("Charlie Puth – Attention (Willcox Remix)"),
                new Music("Desiigner – Panda (Kubski Remix)"),
                new Music("Will K – Sour Milk"),
                new Music("Dan Deal – Trump This"),
                new Music("Selecta – G"),
                new Music("Tiesto & Ummet Ozcan – What You’re Waiting For"),
                new Music("Tommie Sunshine – Scrub The Ground"),
                new Music("Twoloud x Dj Kuba – Mirror on the wall"),
                new Music("J Balvin & Willy William – Mi Gente (Digital Junkiez Remix)"),
                new Music("Tujamo – One on One"),
                new Music("Follow The Flow – Nem tudja senki"),
                new Music("Status Quo – In The Army Now"),
                new Music("CID & Vinne – Take Your Place"),
                new Music("Phlegmatic Dogs – Keepmastik"),
                new Music("PBH & Jack Shizzle – Bring The House"),
                new Music("Gregor Salto – PULA"),
                new Music("Morten & Twoloud – Certified"),
                new Music("Panjabi MC – Mundian To Bach Ke"),
                new Music("Wax Motif – Tokyo"),
                new Music("Destructo – Bassface"),
                new Music("Chocolate Puma – Put It Down"),
                new Music("Twoloud & Bounce Inc. – Bonkers"),
                new Music("Big Shaq & Jauz – The Game"),
                new Music("El Profesor – Bella Ciao (Hugel Remix)"),
                new Music("Pixa – After"),
                new Music("Bingo Players – Don’t Hold Back"),
                new Music("Reebs – Like That"),
                new Music("Status Quo – In The Army Now"),
                new Music("Dom Dolla – Take It"),
                new Music("Bram Fidder – Thirsty"),
                new Music("Malaa – Belleville"),
                new Music("Stupid Goldfish & Dashnation - Sneakers"),
                new Music("Willy William – La La La"),
                new Music("Tiesto & Dzekao ft. Preme & Post Malone – Jackie Chan"),
                new Music("Joer Junior – La Verité"),
                new Music("Twoloud – Mirror On The Wall"),
                new Music("Matisse – Take Off"),
                new Music("Martin Garrix & Khalid – Ocean (Don Diablo Remix)"),
                new Music("Kid Cudi – Day N Nite (Moksi Remix)"),
                new Music("Damien N Drinx – Scratch"),
                new Music("Chocolate Puma – Tear This Mother Down"),
                new Music("Big Shaq x Jauz – The Volume"),
                new Music("Mike Cervello – SMACK! (Moksi Remix)"),
                new Music("Dj Snake – Lets Get Ill"),
                new Music("Status Quo – In The Army Now"),
                new Music("Willy William – La La La"),
                new Music("Bounce Inc – Dump"),
                new Music("Joer Junior – La Verité"),
                new Music("Charlie Puth – Attention (Willcox Remix)"),
                new Music("Desiigner – Panda (Kubski Remix)"),
                new Music("Will K – Sour Milk"),
                new Music("Dan Deal – Trump This"),
                new Music("Selecta – G"),
                new Music("Tiesto & Ummet Ozcan – What You’re Waiting For"),
                new Music("Tommie Sunshine – Scrub The Ground"),
                new Music("Twoloud x Dj Kuba – Mirror on the wall"),
                new Music("J Balvin & Willy William – Mi Gente (Digital Junkiez Remix)"),
                new Music("Tujamo – One on One"),
                new Music("Follow The Flow – Nem tudja senki"),
                new Music("Status Quo – In The Army Now"),
                new Music("Vee Brondi – Fresh"),
                new Music("Sage the Gemini – Now Later"),
                new Music("JoerJunior – Groove"),
                new Music("Dazzo – Hanging Tree"),
                new Music("Fabrizio Delgarco – Morenita"),
                new Music("Keanu Silva – Fine Day"),
                new Music("Chocolate Puma – Put"),
                new Music("Oomloud – Yummy Fun"),
                new Music("Henry Fong – POM POM"),
                new Music("Twoloud x Dj Kuba & Neitan – Mirror On The Wall"),
                new Music("Badmoood & Green Ketchup – Bass From da Block"),
                new Music("Zonderling x Don Diablo – No Good"),
                new Music("Bounce Inc. – Dump"),
                new Music("Martin Garrix – Make Up Your Mind"),
                new Music("Mightyfools – Party Muv"),
                new Music("Status Quo – In The Army Now"),
                new Music("Henry Fong x Lady Bee – POM POM"),
                new Music("Badmood and Green Ketchup – Bass from da Block"),
                new Music("Dj Snake x Mercer – Lets Get Ill"),
                new Music("Big Shaq x Jauz – The"),
                new Music("Reebs – Like that (Extended Mix)"),
                new Music("Camilla Cabello – Havanna (Gabriel B Edit)"),
                new Music("Jauz & Ephwurd – Rock the Party"),
                new Music("Bounce Inc. – Dump"),
                new Music("Damien N-Drix – Scratch"),
                new Music("Zonderling, Don Diablo – No Good"),
                new Music("CID – Werk"),
                new Music("Radiology, Distrion – Monsta (Extended Mix)"),
                new Music("Bleu Clair & Irsan – FTLOH (Extended Mix)"),
                new Music("Tchami, Malaa – Kurupt (Lucati Remix)"),
                new Music("Twoloud, Mairee – What You Got"),
                new Music("Benny Benassi – Satisfaction"),
                new Music("Matroda, Travis Scott – Goosebumbs (Vip Edit)"),
                new Music("Status Quo – In The Army Now"),
                new Music("CID & Vinne – Take Your Place"),
                new Music("Phlegmatic Dogs – Keepmastik"),
                new Music("PBH & Jack Shizzle – Bring The House"),
                new Music("Gregor Salto – PULA"),
                new Music("Morten & Twoloud – Certified"),
                new Music("Panjabi MC – Mundian To Bach Ke"),
                new Music("Wax Motif – Tokyo"),
                new Music("Destructo – Bassface"),
                new Music("Chocolate Puma – Put It Down"),
                new Music("Twoloud & Bounce Inc. – Bonkers"),
                new Music("Big Shaq & Jauz – The Game"),
                new Music("El Profesor – Bella Ciao (Hugel Remix)"),
                new Music("Pixa – After"),
                new Music("Bingo Players – Don’t Hold Back"),
                new Music("Reebs – Like That"),
                new Music("Status Quo – In The Army Now"),
                new Music("Don Diablo – Momentum"),
                new Music("CID – Creepin"),
                new Music("PBH – bring The House"),
                new Music("Tom & Jame – Just Like That"),
                new Music("Cedric Gervais – One Night (D.O.D Remix)"),
                new Music("Christian Marchi – Check Out Da Bass"),
                new Music("Damien N Drix – Ghetto Funk"),
                new Music("BIJOU – Gotta Shine"),
                new Music("Sikdope – Snakes"),
                new Music("Will K – Guamo"),
                new Music("Mike Cervello – SMACK! (Moksi Remix)"),
                new Music("Tommie Sunshine – Scrub The Ground"),
                new Music("Keeld – Action"),
                new Music("Destructo – Bassface"),
                new Music("Status Quo – In The Army Now"),
                new Music("Vee Brondi – Fresh"),
                new Music("Sage the Gemini – Now Later"),
                new Music("JoerJunior – Groove"),
                new Music("Dazzo – Hanging Tree"),
                new Music("Fabrizio Delgarco – Morenita"),
                new Music("Keanu Silva – Fine Day"),
                new Music("Chocolate Puma – Put"),
                new Music("Oomloud – Yummy Fun"),
                new Music("Henry Fong – POM POM"),
                new Music("Twoloud x Dj Kuba & Neitan – Mirror On The Wall"),
                new Music("Badmoood & Green Ketchup – Bass From da Block"),
                new Music("Zonderling x Don Diablo – No Good"),
                new Music("Bounce Inc. – Dump"),
                new Music("Martin Garrix – Make Up Your Mind"),
                new Music("Mightyfools – Party Muv"),
                new Music("Status Quo – In The Army Now"),
                new Music("Joerjunior - Groove"),
                new Music("Relanium & Deen West – Come Back"),
                new Music("Kage – Levitate"),
                new Music("Toby Green – Pulse"),
                new Music("Willcox – Tequila"),
                new Music("Breathe Carolina – DYSYLM"),
                new Music("Dj Snake – Magenta Riddim"),
                new Music("Damien N Drix – Bella Ciao (Hold Up Mix)"),
                new Music("Brothagarx & Mex – Afrojack & Oliver"),
                new Music("Bhaskar – Lose Control"),
                new Music("Kiyoshi, Cazztek – If You Really Wanna"),
                new Music("Lucky Charmes – Warning"),
                new Music("Peter Lowner x DJ TYMO - Free"),
                new Music("Sinden - Cream"),
                new Music("Henry Fong x Lady Bee – POM POM"),
                new Music("Badmood and Green Ketchup – Bass from da Block"),
                new Music("Dj Snake x Mercer – Lets Get Ill"),
                new Music("Reebs – Like that (Extended Mix)"),
                new Music("Camilla Cabello – Havanna (Gabriel B Edit)"),
                new Music("Jauz & Ephwurd – Rock the Party"),
                new Music("Bounce Inc. – Dump"),
                new Music("Damien N-Drix – Scratch"),
                new Music("Zonderling, Don Diablo – No Good"),
                new Music("CID – Werk"),
                new Music("Radiology, Distrion – Monsta (Extended Mix)"),
                new Music("Bleu Clair & Irsan – FTLOH (Extended Mix)"),
                new Music("Tchami, Malaa – Kurupt (Lucati Remix)"),
                new Music("Twoloud, Mairee – What You Got"),
                new Music("Benny Benassi – Satisfaction"),
                new Music("Matroda, Travis Scott – Goosebumbs (Vip Edit)"),
                new Music("Status Quo – In The Army Now"),
                new Music("Liu & Vokker - Don’t Look Back"),
                new Music("Valentino Khan – Lick it (Noizu Remix)"),
                new Music("Dazzo – Hanging Tree"),
                new Music("Steff Da Campo – Get Busy"),
                new Music("Missy Elliot – WTF"),
                new Music("Fedde Le Grand, Funk Machine – Flex"),
                new Music("Mike Cervello – SMACK! (Moksi Remix)"),
                new Music("Tchami, Malaa – Kurupt (Lucati Remix)"),
                new Music("Twoloud & Bounce – Bonkers"),
                new Music("Bhaskar – Lose Control"),
                new Music("JOERJUNIOR – Groove"),
                new Music("Joel Fletcher – Dark Beat"),
                new Music("HI-LO – Ooh La La"),
                new Music("Chris Lawyer – Lula"),
                new Music("Status Quo – In The Army Now"),
                new Music("GTA, Damien N Drix – DunDun"),
                new Music("Charlie Puth – Attention (Willcox Remix)"),
                new Music("Post Malone vs. As I Am, JVST SAY YES – Rockstar vs. Closer"),
                new Music("Twoloud & Bounce Inc. vs Daav One – Bonkers"),
                new Music("Relanium & Deen West & L-DIS – Come Back"),
                new Music("J Balvin & Willy William – Mi Gente (Digital Junkiez Remix)"),
                new Music("Timmy Trumpet & SCNDL – Bleed"),
                new Music("D.O.D. – Sixes"),
                new Music("Dr. Dre & Milk ’N’ Cookies VIP – Still Dre vs. Bassline"),
                new Music("Jauz, Ephwurd – Rock The Party"),
                new Music("Damien N Drix – Wingz"),
                new Music("BLR, Rave & Crave – Taj (Purebeat Edit)"),
                new Music("Fabrizio Delgarco – Morenita (Spalshfunk Remix)"),
                new Music("Wax Motif – Tokyo"),
                new Music("Marten Horger Neon Steve - You Don’t"),
                new Music("Don Diablo – Momentum"),
                new Music("CID – Creepin"),
                new Music("PBH – bring The House"),
                new Music("Tom & Jame – Just Like That"),
                new Music("Cedric Gervais – One Night (D.O.D Remix)"),
                new Music("Christian Marchi – Check Out Da Bass"),
                new Music("Damien N Drix – Ghetto Funk"),
                new Music("BIJOU – Gotta Shine"),
                new Music("Sikdope – Snakes"),
                new Music("Will K – Guamo"),
                new Music("Mike Cervello – SMACK! (Moksi Remix)"),
                new Music("Tommie Sunshine – Scrub The Ground"),
                new Music("Keeld – Action"),
                new Music("Destructo – Bassface"),
                new Music("Status Quo – In The Army Now"),
                new Music("Joerjunior - Groove"),
                new Music("Relanium & Deen West – Come Back"),
                new Music("Kage – Levitate"),
                new Music("Toby Green – Pulse"),
                new Music("Willcox – Tequila"),
                new Music("Breathe Carolina – DYSYLM"),
                new Music("Dj Snake – Magenta Riddim"),
                new Music("Damien N Drix – Bella Ciao (Hold Up Mix)"),
                new Music("Brothagarx & Mex – Afrojack & Oliver"),
                new Music("Bhaskar – Lose Control"),
                new Music("Kiyoshi, Cazztek – If You Really Wanna"),
                new Music("Lucky Charmes – Warning"),
                new Music("Peter Lowner x DJ TYMO - Free"),
                new Music("Sinden - Cream"),
                new Music("El Professor – Bella Ciao (Hugel Remix)"),
                new Music("Wax Motif – Tokyo"),
                new Music("Damien N Drix – Ghetto Funk"),
                new Music("Brothagarx & Mex – Afrojack & Oliver"),
                new Music("Bingo Players – Don’t Hold Back"),
                new Music("Dj Snake – Magenta Riddim"),
                new Music("Brohug – Droppers"),
                new Music("Magnificence – Out Of My Mind"),
                new Music("Mirko Boni – Rio"),
                new Music("Armin Van Buuren – Blah Blah Blah"),
                new Music("Dimatik ft. Monik - Giratina"),
                new Music("Will K vs Fly Project – Café Leche vs Toca"),
                new Music("Tropkillaz – Mambo"),
                new Music("Post Malone – Rockstar"),
                new Music("Magnificence – Cobra"),
                new Music("Status Quo – In The Army Now"),
                new Music("Liu & Vokker - Don’t Look Back"),
                new Music("Valentino Khan – Lick it (Noizu Remix)"),
                new Music("Dazzo – Hanging Tree"),
                new Music("Steff Da Campo – Get Busy"),
                new Music("Missy Elliot – WTF"),
                new Music("Fedde Le Grand, Funk Machine – Flex"),
                new Music("Mike Cervello – SMACK! (Moksi Remix)"),
                new Music("Tchami, Malaa – Kurupt (Lucati Remix)"),
                new Music("Twoloud & Bounce – Bonkers"),
                new Music("Bhaskar – Lose Control"),
                new Music("JOERJUNIOR – Groove"),
                new Music("Joel Fletcher – Dark Beat"),
                new Music("HI-LO – Ooh La La"),
                new Music("Chris Lawyer – Lula"),
                new Music("Status Quo – In The Army Now"),
                new Music("Don Diablo – Momentum"),
                new Music("CID – Creepin"),
                new Music("PBH – bring The House"),
                new Music("Tom & Jame – Just Like That"),
                new Music("Cedric Gervais – One Night (D.O.D Remix)"),
                new Music("Christian Marchi – Check Out Da Bass"),
                new Music("Damien N Drix – Ghetto Funk"),
                new Music("BIJOU – Gotta Shine"),
                new Music("Sikdope – Snakes"),
                new Music("Will K – Guamo"),
                new Music("Mike Cervello – SMACK! (Moksi Remix)"),
                new Music("Tommie Sunshine – Scrub The Ground"),
                new Music("Keeld – Action"),
                new Music("Destructo – Bassface"),
                new Music("Status Quo – In The Army Now"),
                new Music("Joerjunior - Groove"),
                new Music("Relanium & Deen West – Come Back"),
                new Music("Kage – Levitate"),
                new Music("Toby Green – Pulse"),
                new Music("Willcox – Tequila"),
                new Music("Breathe Carolina – DYSYLM"),
                new Music("Dj Snake – Magenta Riddim"),
                new Music("Damien N Drix – Bella Ciao (Hold Up Mix)"),
                new Music("Brothagarx & Mex – Afrojack & Oliver"),
                new Music("Bhaskar – Lose Control"),
                new Music("Kiyoshi, Cazztek – If You Really Wanna"),
                new Music("Lucky Charmes – Warning"),
                new Music("Peter Lowner x DJ TYMO - Free"),
                new Music("Sinden - Cream"),
                new Music("HI-LO – Oh la La"),
                new Music("Wax Motif – Tokyo"),
                new Music("Botnek – Inside The Groove"),
                new Music("Zac Waters – No Quarter"),
                new Music("Lucky Charmes – Party2Night"),
                new Music("Tony Romera – WTTF"),
                new Music("Phlegmatic Dogs – Keepmastik"),
                new Music("Bart B More – Chu Want Dat"),
                new Music("Drop Department – Batucada"),
                new Music("Dj Snake – Magenta Riddim"),
                new Music("Jax Jones – Instructions"),
                new Music("Vini Vici, Astrix – Adhana"),
                new Music("Amin Van Buuren – Great Spirit"),
                new Music("Jauz & Dj Snake – Gassed Up"),
                new Music("Status Quo – In The Army Now"),
                new Music("Joerjunior - Groove"),
                new Music("Relanium & Deen West – Come Back"),
                new Music("Kage – Levitate"),
                new Music("Toby Green – Pulse"),
                new Music("Willcox – Tequila"),
                new Music("Breathe Carolina – DYSYLM"),
                new Music("Dj Snake – Magenta Riddim"),
                new Music("Damien N Drix – Bella Ciao (Hold Up Mix)"),
                new Music("Brothagarx & Mex – Afrojack & Oliver"),
                new Music("Bhaskar – Lose Control"),
                new Music("Kiyoshi, Cazztek – If You Really Wanna"),
                new Music("Lucky Charmes – Warning"),
                new Music("Peter Lowner x DJ TYMO - Free"),
                new Music("Sinden - Cream"),
                new Music("GTA, Damien N Drix – DunDun"),
                new Music("Charlie Puth – Attention (Willcox Remix)"),
                new Music("Post Malone vs. As I Am, JVST SAY YES – Rockstar vs. Closer"),
                new Music("Twoloud & Bounce Inc. vs Daav One – Bonkers"),
                new Music("Relanium & Deen West & L-DIS – Come Back"),
                new Music("J Balvin & Willy William – Mi Gente (Digital Junkiez Remix)"),
                new Music("Timmy Trumpet & SCNDL – Bleed"),
                new Music("D.O.D. – Sixes"),
                new Music("Dr. Dre & Milk ’N’ Cookies VIP – Still Dre vs. Bassline"),
                new Music("Jauz, Ephwurd – Rock The Party"),
                new Music("Damien N Drix – Wingz"),
                new Music("BLR, Rave & Crave – Taj (Purebeat Edit)"),
                new Music("Fabrizio Delgarco – Morenita (Spalshfunk Remix)"),
                new Music("Wax Motif – Tokyo"),
                new Music("Marten Horger Neon Steve - You Don’t"),
                new Music("Moska – This Is House"),
                new Music("GTA, Damien N Drix – DunDun (Original Mix)"),
                new Music("Alma, Felix Jaehn – Bonfire (Chri Lake Remix)"),
                new Music("PBH & Jack Shizz – Bring The House (Extended Mix)"),
                new Music("Skrillex – Chicken Soup"),
                new Music("Timmy Trumpet – Party Till We Die"),
                new Music("Dj Snake – Magenta Riddim (Lumb"),
                new Music("Tony Junior – United"),
                new Music("Bhaskar – Lose Control (Club Mix)"),
                new Music("Camille Cabello – Havanna (Gabriel B Edit)"),
                new Music("Will K – Guamo (Extended Mix)"),
                new Music("Konih – Ready Or Not (Original Mix)"),
                new Music("Damien N Drix – Inkali"),
                new Music("Jauz – Claim To Be"),
                new Music("Skrillex – Would You Ever"),
                new Music("Joel Fletcher & Reece Low- Dark Beat"),
                new Music("Bingo Players- Dont Hold Back"),
                new Music("Havana (gabriel B)"),
                new Music("Merk & Kremont - ciao"),
                new Music("Willcox - tequila"),
                new Music("Jax jones - instruction (gregor salto)"),
                new Music("Selena Gomez - aint me (holl&rush)"),
                new Music("Cristian Marchi-check out da bass"),
                new Music("Global Deejays- work (damien n drix)"),
                new Music("Pbh& javk shizzle - bring the house"),
                new Music("Mirko Boni- rio"),
                new Music("Danny avila nervo- loco"),
                new Music("Chuckie- back in the club"),
                new Music("Zonderling- tunnel vision(don diablo)"),
                new Music("Destructo- bassface"),
                new Music("Status quo- in the army now"),
                new Music("Moska – This Is House"),
                new Music("GTA, Damien N Drix – DunDun (Original Mix)"),
                new Music("Alma, Felix Jaehn – Bonfire (Chri Lake Remix)"),
                new Music("PBH & Jack Shizz – Bring The House (Extended Mix)"),
                new Music("Skrillex – Chicken Soup"),
                new Music("Timmy Trumpet – Party Till We Die"),
                new Music("Dj Snake – Magenta Riddim (Lumb"),
                new Music("Tony Junior – United"),
                new Music("Bhaskar – Lose Control (Club Mix)"),
                new Music("Camille Cabello – Havanna (Gabriel B Edit)"),
                new Music("Will K – Guamo (Extended Mix)"),
                new Music("Konih – Ready Or Not (Original Mix)"),
                new Music("Damien N Drix – Inkali"),
                new Music("Jauz – Claim To Be"),
                new Music("Skrillex – Would You Ever"),
                new Music("GTA, Damien N Drix – DunDun"),
                new Music("Charlie Puth – Attention (Willcox Remix)"),
                new Music("Post Malone vs. As I Am, JVST SAY YES – Rockstar vs. Closer"),
                new Music("Twoloud & Bounce Inc. vs Daav One – Bonkers"),
                new Music("Relanium & Deen West & L-DIS – Come Back"),
                new Music("J Balvin & Willy William – Mi Gente (Digital Junkiez Remix)"),
                new Music("Timmy Trumpet & SCNDL – Bleed"),
                new Music("D.O.D. – Sixes"),
                new Music("Dr. Dre & Milk ’N’ Cookies VIP – Still Dre vs. Bassline"),
                new Music("Jauz, Ephwurd – Rock The Party"),
                new Music("Damien N Drix – Wingz"),
                new Music("BLR, Rave & Crave – Taj (Purebeat Edit)"),
                new Music("Fabrizio Delgarco – Morenita (Spalshfunk Remix)"),
                new Music("Wax Motif – Tokyo"),
                new Music("Marten Horger Neon Steve - You Don’t"),
                new Music("GTA, Damien N Drix – DunDun"),
                new Music("Charlie Puth – Attention (Willcox Remix)"),
                new Music("Post Malone vs. As I Am, JVST SAY YES – Rockstar vs. Closer"),
                new Music("Twoloud & Bounce Inc. vs Daav One – Bonkers"),
                new Music("Relanium & Deen West & L-DIS – Come Back"),
                new Music("J Balvin & Willy William – Mi Gente (Digital Junkiez Remix)"),
                new Music("Timmy Trumpet & SCNDL – Bleed"),
                new Music("D.O.D. – Sixes"),
                new Music("Dr. Dre & Milk ’N’ Cookies VIP – Still Dre vs. Bassline"),
                new Music("Jauz, Ephwurd – Rock The Party"),
                new Music("Damien N Drix – Wingz"),
                new Music("BLR, Rave & Crave – Taj (Purebeat Edit)"),
                new Music("Fabrizio Delgarco – Morenita (Spalshfunk Remix)"),
                new Music("Wax Motif – Tokyo"),
                new Music("Marten Horger Neon Steve - You Don’t"),
                new Music("Joel Fletcher & Reece Low- Dark Beat"),
                new Music("Bingo Players- Dont Hold Back"),
                new Music("Havana (gabriel B)"),
                new Music("Merk & Kremont - ciao"),
                new Music("Willcox - tequila"),
                new Music("Jax jones - instruction (gregor salto)"),
                new Music("Selena Gomez - aint me (holl&rush)"),
                new Music("Cristian Marchi-check out da bass"),
                new Music("Global Deejays- work (damien n drix)"),
                new Music("Pbh& javk shizzle - bring the house"),
                new Music("Mirko Boni- rio"),
                new Music("Danny avila nervo- loco"),
                new Music("Chuckie- back in the club"),
                new Music("Zonderling- tunnel vision(don diablo)"),
                new Music("Destructo- bassface"),
                new Music("Status quo- in the army now"),
                new Music("Bingo Players - Don’t Hold Back"),
                new Music("Lucky Charmes - Warning"),
                new Music("Desiigner - Panda (Kubski Remix)"),
                new Music("Milk & Sugar - Heat (African Day)"),
                new Music("Damien N Drix - Turn It Up"),
                new Music("Mairee - Papapa"),
                new Music("Jeff Nang - Matter Of Time"),
                new Music("Nexboy & Julas - Lick It"),
                new Music("Gianluca - Vacchi Viento"),
                new Music("Joel Fletcher & Reece Low - Dark Beat"),
                new Music("Bingo Players - Don’t Hold Back"),
                new Music("Camile Cabello - Havanna (Gabriel B Edit)"),
                new Music("Merk & Kremont - Ciao"),
                new Music("Willcox - Tequila"),
                new Music("Jax Jones - Instructions (Gregor Salto Remix)"),
                new Music("Kygo, Selena Gomez vs. Roulsen - It Ain’t Rumble (Holl & Rush Mashup)"),
                new Music("Christian Marchi - Check Out Da Bass"),
                new Music("Global Deejays & Danny Marquez - Work (Damien N Drix Remix)"),
                new Music("PBH & Jack Shizzle - Bring The House"),
                new Music("Mirko Boni - Rio"),
                new Music("NERVO, Reverie, Danny Marquez - LOCO"),
                new Music("Chuckie - Back In The Club"),
                new Music("Zonderling - Tunnel Vision (Don Diablo Remix)"),
                new Music("Destructo - Bassface"),
                new Music("Status Quo - In The Army Now"),
                new Music("Bingo Players - Don’t Hold Back"),
                new Music("Lucky Charmes - Warning"),
                new Music("Desiigner - Panda (Kubski Remix)"),
                new Music("Milk & Sugar - Heat (African Day)"),
                new Music("Damien N Drix - Turn It Up"),
                new Music("Mairee - Papapa"),
                new Music("Jeff Nang - Matter Of Time"),
                new Music("Nexboy & Julas - Lick It"),
                new Music("Gianluca - Vacchi Viento"),
                new Music("Joel Fletcher & Reece Low- Dark Beat"),
                new Music("Bingo Players- Dont Hold Back"),
                new Music("Havana (gabriel B)"),
                new Music("Merk & Kremont - ciao"),
                new Music("Willcox - tequila"),
                new Music("Jax jones - instruction (gregor salto)"),
                new Music("Selena Gomez - aint me (holl&rush)"),
                new Music("Cristian Marchi-check out da bass"),
                new Music("Global Deejays- work (damien n drix)"),
                new Music("Pbh& javk shizzle - bring the house"),
                new Music("Mirko Boni- rio"),
                new Music("Danny avila nervo- loco"),
                new Music("Chuckie- back in the club"),
                new Music("Zonderling- tunnel vision(don diablo)"),
                new Music("Destructo- bassface"),
                new Music("Status quo- in the army now"),
                new Music("Tujamo – DropThat Low"),
                new Music("IconaPipfeat. Charlie – I Love It"),
                new Music("Tim van Werd – BounceToThis"),
                new Music("Rihanna, Ummet Ozcan – Turning Umbrella Back"),
                new Music("Kiavetta&ONeils – Levels 1"),
                new Music("HI-LO – RenegadeMastah"),
                new Music("50 Cent vsTujamo – ShakeThatBootyBounce"),
                new Music("HOOX – World Off Music On"),
                new Music("Garmiani, WalshyFire – Vodoo"),
                new Music("DJ Fresh, Diplo – Earhquik"),
                new Music("Carnagefeat. TimmyTrumpet – Toca"),
                new Music("PPAP"),
                new Music("Garmiani – Bomb A Drop"),
                new Music("VINAI & TJR – SevenNationGeneration"),
                new Music("Tujamo – Boom"),
                new Music("50 Cent – PIMP Up"),
                new Music("Swedish House Mafia – One"),
                new Music("Real 2 Real x Will Spark – MoveIt"),
                new Music("KSHMR – Wild Card"),
                new Music("Morten&Twoloud – Certified"),
                new Music("Tom & Jame – Energy"),
                new Music("NickyRomero – Read 2 Rumble"),
                new Music("TommieSunshine – Scrub The Ground"),
                new Music("ZacWaters – No Quarter"),
                new Music("HighlightTribe – Free Tibet"),
                new Music("Showtek – Swipe"),
                new Music("Hardwell, Craig David – No Holding Back"),
                new Music("Thomas Newton Howard – The Hanging Tree"),
                new Music("Martin Solveig - +1 (TujamoRemix)"),
                new Music("Kungsvs. Cookin’ On 3 Burners – ThisGirl"),
                new Music("Bassjackers – El Panda MariachiLano"),
                new Music("Ephwurd – Vibrations"),
                new Music("ContiezFeat. Treyy G – Trumpsta (DjuroRemix)"),
                new Music("Showtekvs Queen – We Will x Booyah"),
                new Music("DMX – Where The Hood"),
                new Music("TJR – WeWannaParty"),
                new Music("Headbunterz – Kundalini"),
                new Music("TimmyTrumpet – Hipsta"),
                new Music("Laidback Luke – Rocking withthebest"),
                new Music("Eiffel 65 &Dannix – BlueClap"),
                new Music("Sikdope – Snakes"),
                new Music("Status Quo – Yamina END"),
                new Music("Teopkillaz- Baby baby (original mix)"),
                new Music("Still DrevsBassline (CTM Mashup)"),
                new Music("Redlight- New Flows"),
                new Music("Tiesto, Svenn- Boom (extended mix)"),
                new Music("Brohug-Droppers"),
                new Music("Flosstradamus Troyboi-Soundclash (Original mix)"),
                new Music("Tujamo ft. Sorana-OneonOne"),
                new Music("Dark Eyez-Malibu (extended mix)"),
                new Music("Zanon- Echos of universe Dang3r remix)"),
                new Music("Chris Lake- I wantyou(original mix)"),
                new Music("Tujamo, PlastinkFunk- WHO (Norby& Roland Bootleg)"),
                new Music("Juicy M. ft. BlimesBrixton-Girl gang (original mix)"),
                new Music("Baby Eazy-E3 – GangstaGangsta (Dr. FreschRemix)"),
                new Music("Sick Individuals - Focus (Extended Mix)"),
                new Music("Skrillex &Habstrakt - ChickenSoup (Original mix)"),
                new Music("D.O.D - Blip (Extended Mix)"),
                new Music("Sonny Banks- Good Girls (Original Mix)"),
                new Music("Timmy Trumpet&Krunk - AlPacino (Extended Mix)"),
                new Music("Matt Nash - ML4U (Original Mix)"),
                new Music("Damien N-Drix& STV - LetIt Ring (Original mix)"),
                new Music("D.O.D - Satisfy (Original Mix)"),
                new Music("Malaa - Belleville (Original mix)"),
                new Music("Luis Fonsi&DaddyYankee - Despacito (Yaminaremix)"),
                new Music("Timmy Turner – Desiigner"),
                new Music("Burak Yeter – Tuesday"),
                new Music("CID, Kaskade – Sweet Memories"),
                new Music("Chocolate Puma & Moksi – Hippo"),
                new Music("Eminem – Without Me"),
                new Music("Damien N Drix – Inkali"),
                new Music("Timmy Trumpet – Bleed"),
                new Music("Roulsen -Rumble"),
                new Music("NERVO – LOCO"),
                new Music("Fedde Le Grand – Love Bad and Boujee"),
                new Music("Tiesto & Sevenn – Boom"),
                new Music("Chuckie – Back in The Club"),
                new Music("Axwell & Ingrosso – More Than You Know"),
                new Music("Tujamo – One On One"),
                new Music("Bern-At & WARLEX – Santa Fckin Claus"),
                new Music("Status Quo – YAMINA END"),
                new Music("Dillon Francis – Say Less"),
                new Music("Damien N Drix – Inkali"),
                new Music("Jax Jones – Instruction"),
                new Music("Dirty Ducks – Medusa"),
                new Music("Hardwell x Brohug – Party Till The Droppers"),
                new Music("Chuckie – Back In The Club"),
                new Music("Roulsen – Rumble"),
                new Music("Bern-At, Warlex – Sante Fckin Claus"),
                new Music("Kendrick Lamar – HUMBLE"),
                new Music("Timmy Trumpet – DejaVu"),
                new Music("Hardwell x Moksi – Powermove"),
                new Music("Konih – This One"),
                new Music("Bingo Players – Don’t Hold Back"),
                new Music("Jauz, Ephwurd – Rock The Party"),
                new Music("Jauz – Claim To Be"),
                new Music("Salento Guys and Paki & Jaro – Bang!"),
                new Music("Damien N Drix – Inkali"),
                new Music("Morten & Twoloud – Certified"),
                new Music("Cobra Effect – Just Be"),
                new Music("Kygo, Selena Gomez & Roulsen – It Ain’t Rumble"),
                new Music("Tiesto & Tony Junior – Get Down"),
                new Music("Gianluca – Vacchi Viento"),
                new Music("Damien N Drix – Turn It Up"),
                new Music("Don Diablo – I’ll House You"),
                new Music("Stadiumx & Metrush – Spacebird"),
                new Music("Bern-At & WARLEX – Santa Fckin Claus"),
                new Music("Firebeatz & Schella vs Dr Dre vs Milk N Cookies – Still Wicked"),
                new Music("Marten Herger, Neon Steve –You Don’t"),
                new Music("Taiki Nulight, Low Steppa – Nose Powder"),
                new Music("Alok & Sevenn – Byob"),
                new Music("Michael Woods – London Baby"),
                new Music("Throttle, Niko The Kid - Pinata"),
                new Music("Damien N Drix – Turn It Up"),
                new Music("Twoloud, Mairee – What You Got"),
                new Music("Dr. Fresch – On and On"),
                new Music("NERVO, Reverie – LOCO"),
                new Music("Brohug – Paparazzi"),
                new Music("Cristian Marchi – Check Out Da Bass"),
                new Music("J Balvin – Mi Gente"),
                new Music("Timmy Trumpet – Al Pacino"),
                new Music("Martin Garrix – Byte"),
                new Music("Tiesto – BOOM"),
                new Music("Curbi – Shinai"),
                new Music("Taiki Nulight, Low Steppa - Warfare"),
                new Music("Status Quo – YAMINA END"),
                new Music("Teopkillaz- Baby baby (original mix)"),
                new Music("Still DrevsBassline (CTM Mashup)"),
                new Music("Redlight- New Flows"),
                new Music("Tiesto, Svenn- Boom (extended mix)"),
                new Music("Brohug-Droppers"),
                new Music("Flosstradamus Troyboi-Soundclash (Original mix)"),
                new Music("Tujamo ft. Sorana-OneonOne"),
                new Music("Dark Eyez-Malibu (extended mix)"),
                new Music("Zanon- Echos of universe Dang3r remix)"),
                new Music("Chris Lake- I wantyou(original mix)"),
                new Music("Tujamo, PlastinkFunk- WHO (Norby& Roland Bootleg)"),
                new Music("Juicy M. ft. BlimesBrixton-Girl gang (original mix)"),
                new Music("Baby Eazy-E3 – GangstaGangsta (Dr. FreschRemix)"),
                new Music("Sick Individuals - Focus (Extended Mix)"),
                new Music("Skrillex &Habstrakt - ChickenSoup (Original mix)"),
                new Music("D.O.D - Blip (Extended Mix)"),
                new Music("Sonny Banks- Good Girls (Original Mix)"),
                new Music("Timmy Trumpet&Krunk - AlPacino (Extended Mix)"),
                new Music("Matt Nash - ML4U (Original Mix)"),
                new Music("Damien N-Drix& STV - LetIt Ring (Original mix)"),
                new Music("D.O.D - Satisfy (Original Mix)"),
                new Music("Malaa - Belleville (Original mix)"),
                new Music("Luis Fonsi&DaddyYankee - Despacito (Yaminaremix)"),
                new Music("Tujamo – DropThat Low"),
                new Music("IconaPipfeat. Charlie – I Love It"),
                new Music("Tim van Werd – BounceToThis"),
                new Music("Rihanna, Ummet Ozcan – Turning Umbrella Back"),
                new Music("Kiavetta&ONeils – Levels 1"),
                new Music("HI-LO – RenegadeMastah"),
                new Music("50 Cent vsTujamo – ShakeThatBootyBounce"),
                new Music("HOOX – World Off Music On"),
                new Music("Garmiani, WalshyFire – Vodoo"),
                new Music("DJ Fresh, Diplo – Earhquik"),
                new Music("Carnagefeat. TimmyTrumpet – Toca"),
                new Music("PPAP"),
                new Music("Garmiani – Bomb A Drop"),
                new Music("VINAI & TJR – SevenNationGeneration"),
                new Music("Tujamo – Boom"),
                new Music("50 Cent – PIMP Up"),
                new Music("Swedish House Mafia – One"),
                new Music("Real 2 Real x Will Spark – MoveIt"),
                new Music("KSHMR – Wild Card"),
                new Music("Morten&Twoloud – Certified"),
                new Music("Tom & Jame – Energy"),
                new Music("NickyRomero – Read 2 Rumble"),
                new Music("TommieSunshine – Scrub The Ground"),
                new Music("ZacWaters – No Quarter"),
                new Music("HighlightTribe – Free Tibet"),
                new Music("Showtek – Swipe"),
                new Music("Hardwell, Craig David – No Holding Back"),
                new Music("Thomas Newton Howard – The Hanging Tree"),
                new Music("Martin Solveig - +1 (TujamoRemix)"),
                new Music("Kungsvs. Cookin’ On 3 Burners – ThisGirl"),
                new Music("Bassjackers – El Panda MariachiLano"),
                new Music("Ephwurd – Vibrations"),
                new Music("ContiezFeat. Treyy G – Trumpsta (DjuroRemix)"),
                new Music("Showtekvs Queen – We Will x Booyah"),
                new Music("DMX – Where The Hood"),
                new Music("TJR – WeWannaParty"),
                new Music("Headbunterz – Kundalini"),
                new Music("TimmyTrumpet – Hipsta"),
                new Music("Laidback Luke – Rocking withthebest"),
                new Music("Eiffel 65 &Dannix – BlueClap"),
                new Music("Sikdope – Snakes"),
                new Music("Status Quo – Yamina END"),
                new Music("D.O.D – Sixes"),
                new Music("Julas – Spinback"),
                new Music("Lucky Charmes – Bring Back Di Bass"),
                new Music("Michael Feiner – Bababa"),
                new Music("Timmy Trumpet – Punjabi"),
                new Music("Sage The Gemini – Now Later (Merk & Kremont Remix)"),
                new Music("The Magician ft. Brayton Bowman – SHY"),
                new Music("Fatboy Slim – Where U Iz (Chocolate Puma Remix)"),
                new Music("Willcox – Shady Baby"),
                new Music("Fraanklyn – Thug Life"),
                new Music("Damien N Drix – Turn It Up"),
                new Music("Martin Solveig - +1 (Tujamo Remix)"),
                new Music("Lucky Charmes – Warning"),
                new Music("Mairee – Papapa (Club Mix)"),
                new Music("Fabrizio Delgarco – Morenita"),
                new Music("Jax Jones – Instruction"),
                new Music("Sikdope – Snakes"),
                new Music("Kygo, Selena Gomez vs Roulsen – It Ain’t Rumble"),
                new Music("YAMINA END – Status Quo"),
                new Music("Throttle, Niko The Kid - Pinata"),
                new Music("Damien N Drix – Turn It Up"),
                new Music("Twoloud, Mairee – What You Got"),
                new Music("Dr. Fresch – On and On"),
                new Music("NERVO, Reverie – LOCO"),
                new Music("Brohug – Paparazzi"),
                new Music("Cristian Marchi – Check Out Da Bass"),
                new Music("J Balvin – Mi Gente"),
                new Music("Timmy Trumpet – Al Pacino"),
                new Music("Martin Garrix – Byte"),
                new Music("Tiesto – BOOM"),
                new Music("Curbi – Shinai"),
                new Music("Taiki Nulight, Low Steppa - Warfare"),
                new Music("Status Quo – YAMINA END"),
                new Music("Mairee – Papapa (Club Mix)"),
                new Music("PBH & Jack Shizzle – Bring The House"),
                new Music("J-Trick, Tom Budin – Heard Right"),
                new Music("Habstrakt, Jace Mek – I Wanna"),
                new Music("Will K – Guamo"),
                new Music("Tujamo – DropThat Low"),
                new Music("IconaPipfeat. Charlie – I Love It"),
                new Music("Tim van Werd – BounceToThis"),
                new Music("Rihanna, Ummet Ozcan – Turning Umbrella Back"),
                new Music("Kiavetta&ONeils – Levels 1"),
                new Music("HI-LO – RenegadeMastah"),
                new Music("50 Cent vsTujamo – ShakeThatBootyBounce"),
                new Music("HOOX – World Off Music On"),
                new Music("Garmiani, WalshyFire – Vodoo"),
                new Music("DJ Fresh, Diplo – Earhquik"),
                new Music("Carnagefeat. TimmyTrumpet – Toca"),
                new Music("PPAP"),
                new Music("Garmiani – Bomb A Drop"),
                new Music("VINAI & TJR – SevenNationGeneration"),
                new Music("Tujamo – Boom"),
                new Music("50 Cent – PIMP Up"),
                new Music("Swedish House Mafia – One"),
                new Music("Real 2 Real x Will Spark – MoveIt"),
                new Music("KSHMR – Wild Card"),
                new Music("Morten&Twoloud – Certified"),
                new Music("Tom & Jame – Energy"),
                new Music("NickyRomero – Read 2 Rumble"),
                new Music("TommieSunshine – Scrub The Ground"),
                new Music("ZacWaters – No Quarter"),
                new Music("HighlightTribe – Free Tibet"),
                new Music("Showtek – Swipe"),
                new Music("Hardwell, Craig David – No Holding Back"),
                new Music("Thomas Newton Howard – The Hanging Tree"),
                new Music("Martin Solveig - +1 (TujamoRemix)"),
                new Music("Kungsvs. Cookin’ On 3 Burners – ThisGirl"),
                new Music("Bassjackers – El Panda MariachiLano"),
                new Music("Ephwurd – Vibrations"),
                new Music("ContiezFeat. Treyy G – Trumpsta (DjuroRemix)"),
                new Music("Showtekvs Queen – We Will x Booyah"),
                new Music("DMX – Where The Hood"),
                new Music("TJR – WeWannaParty"),
                new Music("Headbunterz – Kundalini"),
                new Music("TimmyTrumpet – Hipsta"),
                new Music("Laidback Luke – Rocking withthebest"),
                new Music("Eiffel 65 &Dannix – BlueClap"),
                new Music("Sikdope – Snakes"),
                new Music("Status Quo – Yamina END"),
                new Music("Tim van Werd & Justin St – Bounce To This"),
                new Music("Firebeatz & Schella – Dat Disco Swindle (Extended Mix)"),
                new Music("Laidback Luke & Moska – Get It Right"),
                new Music("Konih – One More (Extended Mix)"),
                new Music("Konih – Ready Or Not"),
                new Music("Mairee – Papapa (Club Mix)"),
                new Music("Calvin Harris – My Way (Massa Remix)"),
                new Music("Garmiani, Julimar Santos – Fogo"),
                new Music("Timmy Trumpet – Bleed Original Mix)"),
                new Music("Morten & Twoloud – Certified"),
                new Music("Oomloud – Break Dat (Original Mix)"),
                new Music("Matt Nash – ML4U (Original Mix)"),
                new Music("Timmy Trumpet – Punjabi (Original Mix)"),
                new Music("Dillon Francis – Say Less"),
                new Music("Mirko Boni – Rio"),
                new Music("Tommie Sunshine – Scrub The Ground"),
                new Music("Tujamo – One On One"),
                new Music("Tchami – Summer 99"),
                new Music("Don Diablo – I’ll House You"),
                new Music("Fedde Le Grand – Love Bad and Boujee"),
                new Music("Don Diablo – Momentum"),
                new Music("Christian Marchi – Check"),
                new Music("Hardwell x Moksi – Powermove"),
                new Music("Mr Virgo – Hypnotical"),
                new Music("YAMINA END – Status Quo"),
                new Music("Tujamo – Drop That Low"),
                new Music("Icona Pip feat. Charlie – I Love It"),
                new Music("Tim van Werd – Bounce To This"),
                new Music("Rihanna, Ummet Ozcan – Turning Umbrella Back"),
                new Music("Kiavetta & ONeils – Levels 1"),
                new Music("HI-LO – Renegade Mastah"),
                new Music("50 Cent vs Tujamo – Shake That Booty Bounce"),
                new Music("HOOX – World Off Music On"),
                new Music("Garmiani, Walshy Fire – Vodoo"),
                new Music("DJ Fresh, Diplo – Earhquik"),
                new Music("Carnage feat. Timmy Trumpet – Toca"),
                new Music("PPAP"),
                new Music("Garmiani – Bomb A Drop"),
                new Music("VINAI & TJR – Seven Nation Generation"),
                new Music("Tujamo – Boom"),
                new Music("50 Cent – PIMP Up"),
                new Music("Swedish House Mafia – One"),
                new Music("Real 2 Real x Will Spark – Move It"),
                new Music("KSHMR – Wild Card"),
                new Music("Morten & Twoloud – Certified"),
                new Music("Tom & Jame – Energy"),
                new Music("Nicky Romero – Read 2 Rumble"),
                new Music("Tommie Sunshine – Scrub The Ground"),
                new Music("Zac Waters – No Quarter"),
                new Music("Highlight Tribe – Free Tibet"),
                new Music("Showtek – Swipe"),
                new Music("Hardwell, Craig David – No Holding Back"),
                new Music("Thomas Newton Howard – The Hanging Tree"),
                new Music("Martin Solveig - +1 (Tujamo Remix)"),
                new Music("Kungs vs. Cookin’ On 3 Burners – This Girl"),
                new Music("Bassjackers – El Panda Mariachi Lano"),
                new Music("Ephwurd – Vibrations"),
                new Music("Contiez Feat. Treyy G – Trumpsta (Djuro Remix)"),
                new Music("Showtek vs Queen – We Will x Booyah"),
                new Music("DMX – Where The Hood"),
                new Music("TJR – We Wanna Party"),
                new Music("Headbunterz – Kundalini"),
                new Music("Timmy Trumpet – Hipsta"),
                new Music("Laidback Luke – Rocking with the best"),
                new Music("Eiffel 65 & Dannix – Blue Clap"),
                new Music("Sikdope – Snakes"),
                new Music("Status Quo – Yamina END"),
                new Music("Dr. Dre – It’s Time"),
                new Music("Who Knows – No ! Sleep"),
                new Music("Fatboy Slim – Where U Iz"),
                new Music("Brohug – Snap"),
                new Music("Dua Lipa – New Rules"),
                new Music("Tchami – Love Language"),
                new Music("Afrojack, Mightyfools – Keep it Low"),
                new Music("Matt Nash – ML4U"),
                new Music("Fedde Le Grand – Coco’s Miracle"),
                new Music("Nicky Romero & Sunne"),
                new Music("Mirko Boni – Rio"),
                new Music("TJR x Joel Fletcher – Rollin"),
                new Music("Lil Debbie – Push"),
                new Music("Phlegmatic Dogs – Keepmastik"),
                new Music("Status Quo – Yamina END"),
                new Music("Lothief – Deep Inside"),
                new Music("Bhaskar & Sevenn – Tam Tam"),
                new Music("Valentino Khan – Pump"),
                new Music("Chocolate Puma – Hippo"),
                new Music("D.O.D – Sixes"),
                new Music("Julas – Spinback"),
                new Music("Lucky Charmes – Bring Back Di Bass"),
                new Music("Michael Feiner – Bababa"),
                new Music("Timmy Trumpet – Punjabi"),
                new Music("Kendrick Lamar – HUMBLE"),
                new Music("Skrillex – Febreze"),
                new Music("Cat Dealers – Your Body"),
                new Music("Matroda – Goosebumbs"),
                new Music("Bart B More – Chu Want Dat"),
                new Music("Habstrakt, Jace Mek – I Wanna"),
                new Music("Status Quo – Yamina END"),
                new Music("Willcox – Strong"),
                new Music("Dark Eyez – Malibu"),
                new Music("Global Deejays & Danny Marquez – Work"),
                new Music("Chuckie – Back in the Club"),
                new Music("Alma, Felix Jaehn – Bonfire (Chris Lake Remix)"),
                new Music("Damien-N-RDrix – Push"),
                new Music("Tim van Werd & Justin St – Bounce To This"),
                new Music("Skrillex – Chicken Soup"),
                new Music("Dropheadz – Kill ’em"),
                new Music("Essentials – Wasted"),
                new Music("Mairee – Papapa"),
                new Music("Mike Hawkins – Hollywood"),
                new Music("Selecta – Turbo"),
                new Music("Throttle – Baddest Behaviour"),
                new Music("Kideko – Crank It, Woah!"),
                new Music("Rihanna – Love On The Brain"),
                new Music("Tujamo – Drop That Low"),
                new Music("Icona Pip feat. Charlie – I Love It"),
                new Music("Tim van Werd – Bounce To This"),
                new Music("Rihanna, Ummet Ozcan – Turning Umbrella Back"),
                new Music("Kiavetta & ONeils – Levels 1"),
                new Music("HI-LO – Renegade Mastah"),
                new Music("50 Cent vs Tujamo – Shake That Booty Bounce"),
                new Music("HOOX – World Off Music On"),
                new Music("Garmiani, Walshy Fire – Vodoo"),
                new Music("DJ Fresh, Diplo – Earhquik"),
                new Music("Carnage feat. Timmy Trumpet – Toca"),
                new Music("PPAP"),
                new Music("Garmiani – Bomb A Drop"),
                new Music("VINAI & TJR – Seven Nation Generation"),
                new Music("Tujamo – Boom"),
                new Music("50 Cent – PIMP Up"),
                new Music("Swedish House Mafia – One"),
                new Music("Real 2 Real x Will Spark – Move It"),
                new Music("KSHMR – Wild Card"),
                new Music("Morten & Twoloud – Certified"),
                new Music("Tom & Jame – Energy"),
                new Music("Nicky Romero – Read 2 Rumble"),
                new Music("Tommie Sunshine – Scrub The Ground"),
                new Music("Zac Waters – No Quarter"),
                new Music("Highlight Tribe – Free Tibet"),
                new Music("Showtek – Swipe"),
                new Music("Hardwell, Craig David – No Holding Back"),
                new Music("Thomas Newton Howard – The Hanging Tree"),
                new Music("Martin Solveig - +1 (Tujamo Remix)"),
                new Music("Kungs vs. Cookin’ On 3 Burners – This Girl"),
                new Music("Bassjackers – El Panda Mariachi Lano"),
                new Music("Ephwurd – Vibrations"),
                new Music("Contiez Feat. Treyy G – Trumpsta (Djuro Remix)"),
                new Music("Showtek vs Queen – We Will x Booyah"),
                new Music("DMX – Where The Hood"),
                new Music("TJR – We Wanna Party"),
                new Music("Headbunterz – Kundalini"),
                new Music("Timmy Trumpet – Hipsta"),
                new Music("Laidback Luke – Rocking with the best"),
                new Music("Eiffel 65 & Dannix – Blue Clap"),
                new Music("Sikdope – Snakes"),
                new Music("Status Quo – Yamina END"),
                new Music("Mairee – Papapa (Club Mix)"),
                new Music("PBH & Jack Shizzle – Bring The House"),
                new Music("J-Trick, Tom Budin – Heard Right"),
                new Music("Habstrakt, Jace Mek – I Wanna"),
                new Music("Paffendorf – Where Are You"),
                new Music("Nicky Romero & Sunnery James – S.O.T.U"),
                new Music("TJR x Joel Fletcher – Rollin"),
                new Music("Malaa – Notorious"),
                new Music("Malaa – Belleville"),
                new Music("Valentino Khan – Pump"),
                new Music("Will K – Guamo"),
                new Music("Eminem – Without Me"),
                new Music("PPAP"),
                new Music("Hannah Wants – Rhytmes"),
                new Music("Thomas Newton Howard – The Hanging Tree"),
                new Music("Status Quo – Yamina End"),
                new Music("Teopkillaz- Baby baby (original mix)"),
                new Music("Still DrevsBassline (CTM Mashup)"),
                new Music("Redlight- New Flows"),
                new Music("Tiesto, Svenn- Boom (extended mix)"),
                new Music("Brohug-Droppers"),
                new Music("Flosstradamus Troyboi-Soundclash (Original mix)"),
                new Music("Tujamo ft. Sorana-OneonOne"),
                new Music("Dark Eyez-Malibu (extended mix)"),
                new Music("Zanon- Echos of universe Dang3r remix)"),
                new Music("Chris Lake- I wantyou(original mix)"),
                new Music("Tujamo, PlastinkFunk- WHO (Norby& Roland Bootleg)"),
                new Music("Juicy M. ft. BlimesBrixton-Girl gang (original mix)"),
                new Music("Baby Eazy-E3 – GangstaGangsta (Dr. FreschRemix)"),
                new Music("Sick Individuals - Focus (Extended Mix)"),
                new Music("Skrillex &Habstrakt - ChickenSoup (Original mix)"),
                new Music("D.O.D - Blip (Extended Mix)"),
                new Music("Sonny Banks- Good Girls (Original Mix)"),
                new Music("Timmy Trumpet&Krunk - AlPacino (Extended Mix)"),
                new Music("Matt Nash - ML4U (Original Mix)"),
                new Music("Damien N-Drix& STV - LetIt Ring (Original mix)"),
                new Music("D.O.D - Satisfy (Original Mix)"),
                new Music("Malaa - Belleville (Original mix)"),
                new Music("Luis Fonsi&DaddyYankee - Despacito (Yaminaremix)"),
                new Music("Mirko Boni – Rio (Original Mix)"),
                new Music("Chocolate Puma & Moks – Hippo Nuteczki"),
                new Music("Laidback Luke – Fcukin Beats"),
                new Music("Hardwell x Moksi – Powermove"),
                new Music("Solberjum – Lose You Fkn Mind"),
                new Music("D.O.D – Trio (Afrojack Edit)"),
                new Music("Timmy Trumpet & SCND – Bleed"),
                new Music("Gregor Salto & Roulsen – PULA (Extended Mix)"),
                new Music("HOOX – World Off Music On"),
                new Music("Konih – One More (Extended Mix)"),
                new Music("Calvin Harris – My Way (Massa Remix)"),
                new Music("Merk amp Kremont Throat – Hit The Road Jack"),
                new Music("Lennard x Gabriel B – Rázzad meg"),
                new Music("KSHMR – Wild Card"),
                new Music("Fabrizio Delgarco – Morenita"),
                new Music("Status Quo – Yamina END"),
                new Music("TRCKLISTA - 2017.08.23. 21H"),
                new Music("Dr. Fresch – On and On"),
                new Music("Kaskade, CID – Sweet Memories"),
                new Music("Malaa – Diamonds (Brohug Remix)"),
                new Music("Brohug – Droppers"),
                new Music("Cobra Effect – Just Be"),
                new Music("Dan Deal – Trump This"),
                new Music("Timmy Trumpet – Party Till We Die"),
                new Music("TJR x Joel Fletcher – Rollin’"),
                new Music("Don Diablo – Cutting Shapes"),
                new Music("TJR – Dik Work"),
                new Music("Sikdope – Snakes"),
                new Music("Skepsis – Goes Like"),
                new Music("Matroda, Travis Scott – Goosebumbs (VIP Edit)"),
                new Music("Phlegmatic Dogs – Keepmastik"),
                new Music("Status Quo – Yamina END"),
                new Music("Teopkillaz- Baby baby (original mix)"),
                new Music("Still DrevsBassline (CTM Mashup)"),
                new Music("Redlight- New Flows"),
                new Music("Tiesto, Svenn- Boom (extended mix)"),
                new Music("Brohug-Droppers"),
                new Music("Flosstradamus Troyboi-Soundclash (Original mix)"),
                new Music("Tujamo ft. Sorana-OneonOne"),
                new Music("Dark Eyez-Malibu (extended mix)"),
                new Music("Zanon- Echos of universe Dang3r remix)"),
                new Music("Chris Lake- I wantyou(original mix)"),
                new Music("Tujamo, PlastinkFunk- WHO (Norby& Roland Bootleg)"),
                new Music("Juicy M. ft. BlimesBrixton-Girl gang (original mix)"),
                new Music("Baby Eazy-E3 – GangstaGangsta (Dr. FreschRemix)"),
                new Music("Sick Individuals - Focus (Extended Mix)"),
                new Music("Skrillex &Habstrakt - ChickenSoup (Original mix)"),
                new Music("D.O.D - Blip (Extended Mix)"),
                new Music("Sonny Banks- Good Girls (Original Mix)"),
                new Music("Timmy Trumpet&Krunk - AlPacino (Extended Mix)"),
                new Music("Matt Nash - ML4U (Original Mix)"),
                new Music("Damien N-Drix& STV - LetIt Ring (Original mix)"),
                new Music("D.O.D - Satisfy (Original Mix)"),
                new Music("Malaa - Belleville (Original mix)"),
                new Music("Luis Fonsi&DaddyYankee - Despacito (Yaminaremix)"),
                new Music("Teopkillaz- Baby baby (original mix)"),
                new Music("Still DrevsBassline (CTM Mashup)"),
                new Music("Redlight- New Flows"),
                new Music("Tiesto, Svenn- Boom (extended mix)"),
                new Music("Brohug-Droppers"),
                new Music("Flosstradamus Troyboi-Soundclash (Original mix)"),
                new Music("Tujamo ft. Sorana-OneonOne"),
                new Music("Dark Eyez-Malibu (extended mix)"),
                new Music("Zanon- Echos of universe Dang3r remix)"),
                new Music("Chris Lake- I wantyou(original mix)"),
                new Music("Tujamo, PlastinkFunk- WHO (Norby& Roland Bootleg)"),
                new Music("Juicy M. ft. BlimesBrixton-Girl gang (original mix)"),
                new Music("Baby Eazy-E3 – GangstaGangsta (Dr. FreschRemix)"),
                new Music("Sick Individuals - Focus (Extended Mix)"),
                new Music("Skrillex &Habstrakt - ChickenSoup (Original mix)"),
                new Music("D.O.D - Blip (Extended Mix)"),
                new Music("Sonny Banks- Good Girls (Original Mix)"),
                new Music("Timmy Trumpet&Krunk - AlPacino (Extended Mix)"),
                new Music("Matt Nash - ML4U (Original Mix)"),
                new Music("Damien N-Drix& STV - LetIt Ring (Original mix)"),
                new Music("D.O.D - Satisfy (Original Mix)"),
                new Music("Malaa - Belleville (Original mix)"),
                new Music("Luis Fonsi&DaddyYankee - Despacito (Yaminaremix)"),
                new Music("Bingo Players – Beat The Drum"),
                new Music("Bijou, Matroda – Famous"),
                new Music("D.O.D. – Unforgettable"),
                new Music("Wax Motif – Tokyo"),
                new Music("Julas – Spinback"),
                new Music("Loud About Us! – Drums"),
                new Music("Tujamo & Chocolate Puma – Who lett he Hippo"),
                new Music("J Balvin & Willy William – Mi gente"),
                new Music("Delayers – Make Them Bounce"),
                new Music("Laidback Luke – Fuckin Beats"),
                new Music("Timmy Trumpet – Bleed"),
                new Music("Valentino Khan – Pump"),
                new Music("Zonderling – Tunnel Vision"),
                new Music("Burak Yeter – Tuesday"),
                new Music("Status Quo – Yamina END"),
                new Music("Nari & Milani – Right Or Wrong"),
                new Music("HI-LO – WTF"),
                new Music("Tony Romera – WTTF"),
                new Music("HI-LO – Ooh La La"),
                new Music("Morten & Twoloud – Certified"),
                new Music("Timmy Trumpet – Al Pacino"),
                new Music("Tiesto – Get Down"),
                new Music("Alesso – Falling"),
                new Music("Bart B More – Chu Want Dat"),
                new Music("Skrillex – Chicken Soup"),
                new Music("JOYRYDE – I Ware House"),
                new Music("Konih – Ready Or Not"),
                new Music("DBN – Mosquito"),
                new Music("Status Quo – Yamina END"),
                new Music("Chocolate Puma – Hippo Nuteczki"),
                new Music("Julas – Spinback"),
                new Music("Axwell, Shapov – Belong (D.O.D Remix)"),
                new Music("The Magician – SHY"),
                new Music("Don Diablo – Momentum (Original Mix)"),
                new Music("Lucky Charmes – Ready (Extended Mix)"),
                new Music("Fedde Le Grand – Love’s Gonna Get You"),
                new Music("PPAP – Pen Pineapple Apple Pen"),
                new Music("Matt Nash – ML4U (Original Mix)"),
                new Music("Stoltenhoff & Mike Cerve – Guerilla (Original Mix)"),
                new Music("Vato Gonzalez, Kris Kiss – Sonic Boom"),
                new Music("Phlegmatic Dogs – Keepmastik"),
                new Music("Lido - Crazy"),
                new Music("Teopkillaz- Baby baby (original mix)"),
                new Music("Still DrevsBassline (CTM Mashup)"),
                new Music("Redlight- New Flows"),
                new Music("Tiesto, Svenn- Boom (extended mix)"),
                new Music("Brohug-Droppers"),
                new Music("Flosstradamus Troyboi-Soundclash (Original mix)"),
                new Music("Tujamo ft. Sorana-OneonOne"),
                new Music("Dark Eyez-Malibu (extended mix)"),
                new Music("Zanon- Echos of universe Dang3r remix)"),
                new Music("Chris Lake- I wantyou(original mix)"),
                new Music("Tujamo, PlastinkFunk- WHO (Norby& Roland Bootleg)"),
                new Music("Juicy M. ft. BlimesBrixton-Girl gang (original mix)"),
                new Music("Baby Eazy-E3 – GangstaGangsta (Dr. FreschRemix)"),
                new Music("Sick Individuals - Focus (Extended Mix)"),
                new Music("Skrillex &Habstrakt - ChickenSoup (Original mix)"),
                new Music("D.O.D - Blip (Extended Mix)"),
                new Music("Sonny Banks- Good Girls (Original Mix)"),
                new Music("Timmy Trumpet&Krunk - AlPacino (Extended Mix)"),
                new Music("Matt Nash - ML4U (Original Mix)"),
                new Music("Damien N-Drix& STV - LetIt Ring (Original mix)"),
                new Music("D.O.D - Satisfy (Original Mix)"),
                new Music("Malaa - Belleville (Original mix)"),
                new Music("Luis Fonsi&DaddyYankee - Despacito (Yaminaremix)"),
                new Music("Liu feat. Vano – Step Ahead"),
                new Music("Dark Eyez – Malibu"),
                new Music("Tujamo & Plastik Funk – Who (Norby & Roland Bootleg)"),
                new Music("Konih – Ready or Not"),
                new Music("Fedde Le Grand – Dancing Together"),
                new Music("Brohug – Droppers"),
                new Music("D.O.D – Sixes"),
                new Music("Gregor Salto – PULA"),
                new Music("Tiesto – Get Down"),
                new Music("Cat Dealers – Your Body"),
                new Music("Chris Lake – I Want You"),
                new Music("Fabrizio Degarco – Morenita"),
                new Music("Tiesto – Boom"),
                new Music("Timmy Trumpet – Al Pacino"),
                new Music("Usher – Tell Me"),
                new Music("DMX – Where The Hood At"),
                new Music("Ed Sheeran – Shape Of You"),
                new Music("Calvin Harris – My Way"),
                new Music("Cobra Effect – Just Be"),
                new Music("Baha Men vs Tujamo – Who Lett he Dogs Out"),
                new Music("Skrillex – Chicken Soup"),
                new Music("Desiigner, Skrillex – Panda vs Purple Lamborghini"),
                new Music("TJR ft. Savage – We Wanna Party"),
                new Music("Carnage – Toca"),
                new Music("Luis FOnsi & Daddy Yankee – Despacito"),
                new Music("Mightyfools – Girl On Girl"),
                new Music("Timmy Trumpet – Party Till We Die"),
                new Music("DJ Fresh, Diplo – Earthquik"),
                new Music("Showtek – We Will"),
                new Music("Don Diablo – Let Me Love You"),
                new Music("Eurythmics – Sweet Peak Dreams"),
                new Music("PPAP – Pen Pineapple Apple Pen"),
                new Music("Danny Avila – C.H.E.C.K."),
                new Music("Flosstradamus – Soundclash"),
                new Music("Daddy Yankee – Gasolina"),
                new Music("Jewelz – Motor"),
                new Music("Wiwek – Angry Birdz"),
                new Music("Sia & Sbeastian Ingrosso – Cheap Thrills"),
                new Music("Dan Deal – Trump This"),
                new Music("Headhunterz & Skytech – Kundalini"),
                new Music("Snoop Dogg Dr Dre – The Next Freaks"),
                new Music("The Chainsmokers – Don’t Let Me Down"),
                new Music("Sweet Memories (Extended Mix) - Kaskade, CID"),
                new Music("Blip (Extended Mix) - D.O.D"),
                new Music("Panda (kubski remix) - Desiigner"),
                new Music("Where U Iz (Chocolate Puma Remix) - Fatboy Slim"),
                new Music("Eminem - Without Me (Syskey Remix)"),
                new Music("What You're Waiting For (Extended Mix) - Tiesto & Ummet Ozcan"),
                new Music("Calabria 2017 - FIZBOH"),
                new Music("Al Pacino (Extended Mix) - Timmy Trumpet & Krunk"),
                new Music("Trump This (Original mix) - Dan Deal"),
                new Music("Dik Work (feat. DJ Funk) - TJR"),
                new Music("Chicken Soup - Skrillex & Habstrakt"),
                new Music("Fcukin Beats (Original Mix) - Laidback Luke, twoloud"),
                new Music("Just Be (yamina cut) - Cobra Effect"),
                new Music("Good Girls (Original Mix) - Sonny Banks"),
            };
        }
    }
}
